ALTER TABLE `account_access` ENGINE=INNODB;
ALTER TABLE `account` ENGINE=INNODB;
ALTER TABLE `account_banned` ENGINE=INNODB;
ALTER TABLE `ip_banned` ENGINE=INNODB;
ALTER TABLE `logs` ENGINE=INNODB;
ALTER TABLE `realmcharacters` ENGINE=INNODB;
ALTER TABLE `realmlist` ENGINE=INNODB;
ALTER TABLE `uptime` ENGINE=INNODB;
