/*
 * Copyright (C) 2008-2013 TrinityCore <http://www.trinitycore.org/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _CHARACTERDATABASE_H
#define _CHARACTERDATABASE_H

#include "DatabaseWorkerPool.h"
#include "MySQLConnection.h"

class CharacterDatabaseConnection : public MySQLConnection
{
    public:
        //- Constructors for sync and async connections
        CharacterDatabaseConnection(MySQLConnectionInfo& connInfo) : MySQLConnection(connInfo) {}
        CharacterDatabaseConnection(ACE_Activation_Queue* q, MySQLConnectionInfo& connInfo) : MySQLConnection(q, connInfo) {}

        //- Loads database type specific prepared statements
        void DoPrepareStatements();
};

typedef DatabaseWorkerPool<CharacterDatabaseConnection> CharacterDatabaseWorkerPool;

enum CharacterDatabaseStatements
{
    /*  Naming standard for defines:
        {DB}_{SEL/INS/UPD/DEL/REP}_{Summary of data changed}
        When updating more than one field, consider looking at the calling function
        name for a suiting suffix.
    */

    // Account
    CHAR_SELECT_ACCOUNT_DATA,
    CHAR_REPLACE_ACCOUNT_DATA,
    CHAR_DELETE_ACCOUNT_DATA,
    CHAR_SELECT_CHARACTER_ACCOUNT_DATA,
    CHAR_REPLACE_PLAYER_ACCOUNT_DATA,
    CHAR_DELETE_PLAYER_ACCOUNT_DATA, 
    CHAR_SELECT_ACCOUNT_BY_NAME,
    CHAR_SELECT_ACCOUNT_BY_GUID,
    CHAR_DELETE_ACCOUNT_INSTANCE_LOCK_TIMES,
    CHAR_INSERT_ACCOUNT_INSTANCE_LOCK_TIMES,
    CHAR_UPDATE_ACCOUNT_ONLINE,
    CHAR_UPDATE_ADD_AT_LOGIN_FLAG,
    CHAR_UPDATE_REM_AT_LOGIN_FLAG,
    CHAR_UPDATE_ALL_AT_LOGIN_FLAGS,
    CHAR_DELETE_DECLINED_NAME,

    // Misc
    CHAR_SELECT_CHARACTER_COUNT,
    CHAR_DELETE_QUEST_POOL_SAVE,
    CHAR_INSERT_QUEST_POOL_SAVE,
    CHAR_SELECT_GUID_BY_NAME,
    CHAR_SELECT_GUID_BY_NAME_FILTER,
    CHAR_SELECT_CHECK_NAME,
    CHAR_SELECT_CHECK_GUID,
    CHAR_SELECT_SUM_CHARS,
    CHAR_SELECT_CHAR_CREATE_INFO,
    CHAR_INSERT_BUG_REPORT,

    // Bans
    CHAR_INSERT_CHARACTER_BAN,
    CHAR_UPDATE_CHARACTER_BAN,
    CHAR_DELETE_EXPIRED_BANS,
    CHAR_SELECT_BAN_INFO,
    CHAR_SELECT_BAN_INFO_LIST,
    CHAR_SELECT_BANNED_NAME,
    CHAR_SELECT_ENUM,
    CHAR_SELECT_ENUM_DECLINED_NAME,
    CHAR_SELECT_FREE_NAME,
    CHAR_SELECT_GUID_RACE_ACC_BY_NAME,
    CHAR_SELECT_CHAR_RACE,
    CHAR_SELECT_CHAR_LEVEL,
    CHAR_SELECT_CHAR_ZONE,
    CHAR_SELECT_CHARACTER_NAME_DATA,
    CHAR_SELECT_CHAR_POSITION_XYZ,
    CHAR_SELECT_CHAR_POSITION,

    // Character loading
    CHAR_SELECT_CHARACTER,
    CHAR_SELECT_GROUP_MEMBER,
    CHAR_SELECT_CHARACTER_INSTANCE,
    CHAR_SELECT_CHARACTER_AURAS,
    CHAR_SELECT_CHARACTER_SPELL,
    CHAR_SELECT_CHARACTER_QUEST_STATUS,
    CHAR_SELECT_CHARACTER_DAILY_QUEST_STATUS,
    CHAR_SELECT_CHARACTER_WEEKLY_QUEST_STATUS,
    CHAR_SELECT_CHARACTER_SEASONAL_QUEST_STATUS,
    CHAR_INSERT_CHARACTER_DAILY_QUEST_STATUS,
    CHAR_INSERT_CHARACTER_WEEKLY_QUEST_STATUS,
    CHAR_INSERT_CHARACTER_SEASONAL_QUEST_STATUS,
    CHAR_SELECT_CHARACTER_REPUTATION,
    CHAR_SELECT_CHARACTER_INVENTORY,
    CHAR_SELECT_CHARACTER_ACTIONS,
    CHAR_SELECT_CHARACTER_ACTIONS_SPEC,
    CHAR_SELECT_CHARACTER_MAILCOUNT,
    CHAR_SELECT_CHARACTER_MAILDATE,
    CHAR_SELECT_MAIL_COUNT,    
    CHAR_SELECT_CHARACTER_SOCIAL_LIST,
    CHAR_SELECT_CHARACTER_HOME_BIND,
    CHAR_SELECT_CHARACTER_SPELL_COOLDOWNS,
    CHAR_SELECT_CHARACTER_DECLINED_NAMES,
    CHAR_SELECT_CHARACTER_GUILD,
    CHAR_SELECT_CHARACTER_ARENA_INFO,
    CHAR_SELECT_CHARACTER_ACHIEVEMENTS,
    CHAR_SELECT_CHARACTER_CRITERIA_PROGRESS,
    CHAR_SELECT_CHARACTER_EQUIPMENT_SETS,
    CHAR_SELECT_CHARACTER_BG_DATA,
    CHAR_SELECT_CHARACTER_GLYPHS,
    CHAR_SELECT_CHARACTER_TALENTS,
    CHAR_SELECT_CHARACTER_SKILLS,
    CHAR_SELECT_CHARACTER_RANDOM_BG,
    CHAR_SELECT_CHARACTER_BANNED,
    CHAR_SELECT_CHARACTER_QUEST_STATUS_REW,
    CHAR_SELECT_ACCOUNT_INSTANCE_LOCK_TIMES,
    CHAR_SELECT_MAIL_ITEMS,
    CHAR_SELECT_CHARACTER_NAME_CLASS,
    CHAR_SELECT_CHARACTER_NAME,   
    CHAR_SELECT_ACCOUNT_NAME_BY_GUID,    
    CHAR_DELETE_QUEST_STATUS_DAILY,
    CHAR_DELETE_QUEST_STATUS_WEEKLY,
    CHAR_DELETE_QUEST_STATUS_SEASONAL,
    CHAR_DELETE_QUEST_STATUS_DAILY_CHAR,
    CHAR_DELETE_QUEST_STATUS_WEEKLY_CHAR,
    CHAR_DELETE_QUEST_STATUS_SEASONAL_CHAR,
    CHAR_DELETE_BATTLEGROUND_RANDOM,
    CHAR_INSERT_BATTLEGROUND_RANDOM,
    CHAR_SELECT_GUILD_ID,

    // Auction
    CHAR_SELECT_AUCTION_ITEMS,
    CHAR_INSERT_AUCTION,
    CHAR_DELETE_AUCTION,
    CHAR_SELECT_AUCTION_BY_TIME,    
    CHAR_SELECT_AUCTIONS,
    CHAR_SELECT_EXPIRED_AUCTIONS,

    // Mails
    CHAR_INSERT_MAIL,
    CHAR_DELETE_MAIL,
    CHAR_INSERT_MAIL_ITEM,
    CHAR_DELETE_MAIL_ITEM,
    CHAR_DELETE_INVALID_MAIL_ITEM,
    CHAR_DELETE_EMPTY_EXPIRED_MAIL,
    CHAR_SELECT_EXPIRED_MAIL,
    CHAR_SELECT_EXPIRED_MAIL_ITEMS,
    CHAR_UPDATE_MAIL_RETURNED,
    CHAR_UPDATE_MAIL_ITEM_RECEIVER,

    // Items
    CHAR_UPDATE_ITEM_OWNER,
    CHAR_DELETE_NONEXISTENT_GUILD_BANK_ITEM,
    CHAR_SELECT_GUILD_BANK_ITEMS,
    CHAR_SELECT_ITEM_REFUNDS,
    CHAR_SELECT_ITEM_BOP_TRADE,
    CHAR_DELETE_ITEM_BOP_TRADE,
    CHAR_INSERT_ITEM_BOP_TRADE,
    CHAR_REPLACE_INVENTORY_ITEM,
    CHAR_DELETE_INVENTORY_ITEM,
    CHAR_REPLACE_ITEM_INSTANCE,
    CHAR_UPDATE_ITEM_INSTANCE,
    CHAR_UPDATE_ITEM_INSTANCE_ON_LOAD,
    CHAR_DELETE_ITEM_INSTANCE,
    CHAR_UPDATE_GIFT_OWNER,
    CHAR_DELETE_GIFT,
    CHAR_SELECT_CHARACTER_GIFT_BY_ITEM,
   
    // Guild handling
    CHAR_INSERT_GUILD,
    CHAR_DELETE_GUILD,
    CHAR_INSERT_GUILD_MEMBER,
    CHAR_DELETE_GUILD_MEMBER,
    CHAR_DELETE_GUILD_MEMBERS,
    CHAR_INSERT_GUILD_RANK,
    CHAR_DELETE_GUILD_RANKS,
    CHAR_DELETE_GUILD_LOWEST_RANK,
    CHAR_INSERT_GUILD_BANK_TAB,
    CHAR_DELETE_GUILD_BANK_TAB,
    CHAR_DELETE_GUILD_BANK_TABS,
    CHAR_INSERT_GUILD_BANK_ITEM,
    CHAR_DELETE_GUILD_BANK_ITEM,
    CHAR_DELETE_GUILD_BANK_ITEMS,
    CHAR_INSERT_GUILD_BANK_RIGHT_DEFAULT,
    CHAR_INSERT_GUILD_BANK_RIGHT,
    CHAR_DELETE_GUILD_BANK_RIGHT,
    CHAR_DELETE_GUILD_BANK_RIGHTS,
    CHAR_DELETE_GUILD_BANK_RIGHTS_FOR_RANK,
    CHAR_INSERT_GUILD_BANK_EVENTLOG,
    CHAR_DELETE_GUILD_BANK_EVENTLOG,
    CHAR_DELETE_GUILD_BANK_EVENTLOGS,
    CHAR_INSERT_GUILD_EVENTLOG,
    CHAR_DELETE_GUILD_EVENTLOG,
    CHAR_DELETE_GUILD_EVENTLOGS,
    CHAR_UPDATE_GUILD_MEMBER_PNOTE,
    CHAR_UPDATE_GUILD_MEMBER_OFFNOTE,
    CHAR_UPDATE_GUILD_MEMBER_RANK,
    CHAR_UPDATE_GUILD_MOTD,
    CHAR_UPDATE_GUILD_INFO,
    CHAR_UPDATE_GUILD_LEADER,
    CHAR_UPDATE_GUILD_RANK_NAME,
    CHAR_UPDATE_GUILD_RANK_RIGHTS,
    CHAR_UPDATE_GUILD_SAVE_XP,
    CHAR_SELECT_GUILD_NEWS,
    CHAR_INSERT_GUILD_NEWS,
    CHAR_UPDATE_GUILD_EMBLEM_INFO,
    CHAR_UPDATE_GUILD_BANK_TAB_INFO,
    CHAR_UPDATE_GUILD_BANK_MONEY,
    CHAR_UPDATE_GUILD_BANK_EVENTLOG_TAB,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_MONEY,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_MONEY,
    CHAR_UPDATE_GUILD_RANK_BANK_RESET_TIME,
    CHAR_UPDATE_GUILD_RANK_BANK_MONEY,
    CHAR_UPDATE_GUILD_BANK_TAB_TEXT,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS0,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS1,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS2,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS3,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS4,
    CHAR_UPDATE_GUILD_MEMBER_BANK_TIME_REM_SLOTS5,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS0,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS1,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS2,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS3,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS4,
    CHAR_UPDATE_GUILD_MEMBER_BANK_REM_SLOTS5,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME0,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME1,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME2,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME3,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME4,
    CHAR_UPDATE_GUILD_RANK_BANK_TIME5,
    CHAR_SELECT_CHAR_DATA_FOR_GUILD,

    // Chat channel handling
    CHAR_SELECT_CHANNEL,
    CHAR_INSERT_CHANNEL,
    CHAR_UPDATE_CHANNEL,
    CHAR_UPDATE_CHANNEL_USAGE,
    CHAR_UPDATE_CHANNEL_OWNERSHIP,
    CHAR_DELETE_OLD_CHANNELS,

    // Equipment Sets
    CHAR_UPDATE_EQUIP_SET,
    CHAR_INSERT_EQUIP_SET,
    CHAR_DELETE_EQUIP_SET,

    // Auras
    CHAR_DELETE_AURA,
    CHAR_INSERT_AURA,

    // Currency
    CHAR_SELECT_CHARACTER_CURRENCY,
    CHAR_SELECT_CHARACTER_CP_WEEK_CAP, // conquest points
    CHAR_SELECT_CP_VAL,

    // Tutorials
    CHAR_SELECT_TUTORIALS,
    CHAR_SELECT_HAS_TUTORIALS,
    CHAR_INSERT_TUTORIALS,
    CHAR_UPDATE_TUTORIALS,
    CHAR_DELETE_TUTORIALS,

    // Instance Saves
    CHAR_INSERT_INSTANCE_SAVE,
    CHAR_UPDATE_INSTANCE_DATA,

    // Game Events
    CHAR_DELETE_GAME_EVENT_SAVE,
    CHAR_INSERT_GAME_EVENT_SAVE,
    CHAR_DELETE_ALL_GAME_EVENT_CONDITION_SAVE,
    CHAR_DELETE_GAME_EVENT_CONDITION_SAVE,
    CHAR_INSERT_GAME_EVENT_CONDITION_SAVE,

    // Petitions
    CHAR_SELECT_PETITION,
    CHAR_SELECT_PETITION_SIGNATURE,
    CHAR_DELETE_ALL_PETITION_SIGNATURES,
    CHAR_DELETE_PETITION_SIGNATURE,
    CHAR_UPDATE_PETITION_NAME,
    CHAR_INSERT_PETITION_SIGNATURE,
    CHAR_SELECT_PETITION_BY_OWNER,
    CHAR_SELECT_PETITION_TYPE,
    CHAR_SELECT_PETITION_SIGNATURES,
    CHAR_SELECT_PETITION_SIG_BY_ACCOUNT,
    CHAR_SELECT_PETITION_OWNER_BY_GUID,
    CHAR_SELECT_PETITION_SIG_BY_GUID,
    CHAR_SELECT_PETITION_SIG_BY_GUID_TYPE,
    
    // Arena Teams
    CHAR_INSERT_ARENA_TEAM,
    CHAR_DELETE_ARENA_TEAM,
    CHAR_DELETE_ARENA_TEAM_MEMBERS,
    CHAR_UPDATE_ARENA_TEAM_CAPTAIN,
    CHAR_DELETE_ARENA_TEAM_MEMBER,
    CHAR_UPDATE_ARENA_TEAM_STATS,
    CHAR_INSERT_ARENA_TEAM_MEMBER,
    CHAR_UPDATE_ARENA_TEAM_MEMBER,
    CHAR_REPLACE_CHARACTER_ARENA_STATS,
    CHAR_SELECT_CHARACTER_ARENA_TEAMS,
    CHAR_SELECT_MATCH_MAKER_RATING,

    // Character battleground data
    CHAR_INSERT_PLAYER_BGDATA,
    CHAR_DELETE_PLAYER_BGDATA,

    // Homebind
    CHAR_INSERT_PLAYER_HOMEBIND,
    CHAR_UPDATE_PLAYER_HOMEBIND,
    CHAR_DELETE_PLAYER_HOMEBIND,

    // Corpse
    CHAR_SELECT_CORPSES,
    CHAR_INSERT_CORPSE,
    CHAR_DELETE_CORPSE,
    CHAR_DELETE_PLAYER_CORPSES,
    CHAR_DELETE_OLD_CORPSES,

    // Creature respawn
    CHAR_SELECT_CREATURE_RESPAWNS,
    CHAR_REPLACE_CREATURE_RESPAWNS,
    CHAR_DELETE_CREATURE_RESPAWNS,
    CHAR_DELETE_CREATURE_RESPAWN_BY_GUID,
    CHAR_DELETE_CREATURE_RESPAWN_BY_INSTANCE,
    CHAR_SELECT_MAX_CREATURE_RESPAWNS,

    // Gameobject respawn
    CHAR_SELECT_GO_RESPAWNS,
    CHAR_REPLACE_GO_RESPAWNS,
    CHAR_DELETE_GO_RESPAWNS,
    CHAR_DELETE_GO_RESPAWNS_BY_INSTANCE,

    // GM tickets
    CHAR_SELECT_GM_TICKETS,
    CHAR_REPLACE_GM_TICKETS,
    CHAR_DELETE_ALL_GM_TICKETS,
    CHAR_DELETE_GM_TICKETS,
    CHAR_DELETE_PLAYER_GM_TICKETS,

    // GM survey
    CHAR_INSERT_GM_SURVEY,
    CHAR_INSERT_GM_SUBSURVEY,
    CHAR_INSERT_LAG_REPORT,

    // Pet
    CHAR_SELECT_PET_SLOTS,
    CHAR_SELECT_PET_SLOTS_DETAIL,
    CHAR_SELECT_PET_ENTRY,
    CHAR_SELECT_PET_SLOT_BY_ID,

    CHAR_INSERT_CHARACTER,
    CHAR_UPDATE_CHARACTER,

    CHAR_INSERT_GROUP,
    CHAR_INSERT_GROUP_MEMBER,
    CHAR_DELETE_GROUP_MEMBER,
    CHAR_DELETE_GROUP_INSTANCE_PERM_BINDING,
    CHAR_UPDATE_GROUP_LEADER,
    CHAR_UPDATE_GROUP_TYPE,
    CHAR_UPDATE_GROUP_MEMBER_SUBGROUP,
    CHAR_UPDATE_GROUP_MEMBER_FLAG,
    CHAR_UPDATE_GROUP_DIFFICULTY,
    CHAR_UPDATE_GROUP_RAID_DIFFICULTY,
    CHAR_DELETE_INVALID_SPELL,
    CHAR_UPDATE_DELETE_INFO,
    CHAR_UDP_RESTORE_DELETE_INFO,
    CHAR_UPDATE_ZONE,
    CHAR_UPDATE_LEVEL,
    CHAR_DELETE_INVALID_ACHIEV_PROGRESS_CRITERIA,
    CHAR_DELETE_INVALID_ACHIEVMENT,
    CHAR_INSERT_ADDON,
    CHAR_DELETE_INVALID_PET_SPELL,
    CHAR_DELETE_GROUP_INSTANCE_BY_INSTANCE,
    CHAR_DELETE_GROUP_INSTANCE_BY_GUID,
    CHAR_REPLACE_GROUP_INSTANCE,
    CHAR_UPDATE_INSTANCE_RESETTIME,
    CHAR_UPDATE_GLOBAL_INSTANCE_RESETTIME,
    CHAR_UPDATE_CHAR_ONLINE,
    CHAR_UPDATE_CHAR_NAME_AT_LOGIN,
    CHAR_UPDATE_WORLDSTATE,
    CHAR_INSERT_WORLDSTATE,
    CHAR_DELETE_CHAR_INSTANCE,
    CHAR_UPDATE_CHAR_INSTANCE,
    CHAR_INSERT_CHAR_INSTANCE,
    CHAR_UPDATE_GENDER_PLAYERBYTES,
    CHAR_DELETE_CHARACTER_SKILL,
    CHAR_UPDATE_ADD_CHARACTER_SOCIAL_FLAGS,
    CHAR_UPDATE_REM_CHARACTER_SOCIAL_FLAGS,
    CHAR_INSERT_CHARACTER_SOCIAL,
    CHAR_DELETE_CHARACTER_SOCIAL,
    CHAR_UPDATE_CHARACTER_SOCIAL_NOTE,
    CHAR_UPDATE_CHARACTER_POSITION,

    CHAR_INSERT_LFG_DATA,
    CHAR_DELETE_LFG_DATA,

    CHAR_SELECT_CHARACTER_AURA_FROZEN,
    CHAR_SELECT_CHARACTER_ONLINE,

    CHAR_SELECT_CHAR_DELETE_INFO_BY_GUID,
    CHAR_SELECT_CHAR_DELETE_INFO_BY_NAME,
    CHAR_SELECT_CHAR_DELETE_INFO,

    CHAR_SELECT_CHARS_BY_ACCOUNT_ID,
    CHAR_SELECT_CHAR_PINFO,
    CHAR_SELECT_PINFO_BANS,
    CHAR_SELECT_CHAR_HOMEBIND,
    CHAR_SELECT_CHAR_GUID_NAME_BY_ACC,
    CHAR_SELECT_POOL_QUEST_SAVE,
    CHAR_SELECT_CHARACTER_AT_LOGIN,
    CHAR_SELECT_CHAR_CLASS_LVL_AT_LOGIN,
    CHAR_SELECT_INSTANCE,
    CHAR_SELECT_CHAR_COD_ITEM_MAIL,
    CHAR_SELECT_CHAR_SOCIAL,
    CHAR_SELECT_CHAR_OLD_CHARS,
    CHAR_SELECT_ARENA_TEAM_ID_BY_PLAYER_GUID,
    CHAR_SELECT_MAIL,
    CHAR_SELECT_CHAR_PLAYERBYTES2,
    CHAR_SELECT_CHAR_GUID_BY_NAME,
    CHAR_DELETE_CHAR_AURA_FROZEN,
    CHAR_SELECT_CHAR_INVENTORY_COUNT_ITEM,
    CHAR_SELECT_MAIL_COUNT_ITEM,
    CHAR_SELECT_AUCTIONHOUSE_COUNT_ITEM,
    CHAR_SELECT_GUILD_BANK_COUNT_ITEM,
    CHAR_SELECT_CHAR_INVENTORY_ITEM_BY_ENTRY,
    CHAR_SELECT_MAIL_ITEMS_BY_ENTRY,
    CHAR_SELECT_AUCTIONHOUSE_ITEM_BY_ENTRY,
    CHAR_SELECT_GUILD_BANK_ITEM_BY_ENTRY,
    
    MAX_CHARACTERDATABASE_STATEMENTS,
};

#endif
