/*
 * Copyright (C) 2010-2011 Project SkyFire <http://www.projectskyfire.org/>
 * Copyright (C) 2008-2011 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

// Note: this include need for be sure have full definition of class WorldSession
//       if this class definition not complete then VS for x64 release use different size for
//       struct OpcodeHandler in this header and Opcode.cpp and get totally wrong data from
//       table opcodeTable in source when Opcode.h included but WorldSession.h not included

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"
#include "WorldSession.h"

#define OPCODE_NOT_FOUND 0x10000

/// List of Opcodes
enum Opcodes
{
    CMSG_WORLD_TELEPORT                              = 0x10000, //
    CMSG_TELEPORT_TO_UNIT                            = 0x10001, //
    SMSG_CHECK_FOR_BOTS                              = 0x10002, //
    CMSG_BOT_DETECTED2                               = 0x10003, //
    SMSG_FORCEACTIONSHOW                             = 0x10004, //
    SMSG_PETGODMODE                                  = 0x10005, //
    SMSG_GODMODE                                     = 0x10006, //
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                = 0x10007, //
    CMSG_CHAR_CREATE                                 = 0x02A86, // 4.3.0 15050
    CMSG_CHAR_ENUM                                   = 0x04B06, // 4.3.0 15050
    CMSG_CHAR_DELETE                                 = 0x038A4, // 4.3.0 15050
    SMSG_CHAR_CREATE                                 = 0x02A82, // 4.3.0 15050
    SMSG_CHAR_ENUM                                   = 0x004AC, // 4.3.0 15050
    SMSG_CHAR_DELETE                                 = 0x02A02, // 4.3.0 15050
    CMSG_PLAYER_LOGIN                                = 0x00326, // 4.3.0 15050
    SMSG_NEW_WORLD                                   = 0x064AC, // 4.3.0 15050
    SMSG_TRANSFER_PENDING                            = 0x10009, //
    SMSG_TRANSFER_ABORTED                            = 0x1000A, //
    SMSG_CHARACTER_LOGIN_FAILED                      = 0x04E00, // 4.3.0 15050
    SMSG_LOGIN_SETTIMESPEED                          = 0x02002, // 4.3.0 15050
    SMSG_GAMETIME_UPDATE                             = 0x01800, // 4.3.0 15050
    CMSG_GAMETIME_SET                                = 0x03202, // 4.3.0 15050
    SMSG_GAMETIME_SET                                = 0x1000F, //
    CMSG_GAMESPEED_SET                               = 0x10010, //
    SMSG_GAMESPEED_SET                               = 0x10011, //
    CMSG_SERVERTIME                                  = 0x10012, //
    SMSG_SERVERTIME                                  = 0x02680, // 4.3.0 15050
    CMSG_PLAYER_LOGOUT                               = 0x10014, //
    CMSG_LOGOUT_REQUEST                              = 0x10015, //
    SMSG_LOGOUT_RESPONSE                             = 0x10016, //
    SMSG_LOGOUT_COMPLETE                             = 0x10017, //
    CMSG_LOGOUT_CANCEL                               = 0x10018, //
    SMSG_LOGOUT_CANCEL_ACK                           = 0x10019, //
    CMSG_NAME_QUERY                                  = 0x07220, // 4.3.0 15050
    SMSG_NAME_QUERY_RESPONSE                         = 0x05E20, // 4.3.0 15050
    CMSG_PET_NAME_QUERY                              = 0x00AA2, // 4.3.0 15050
    SMSG_PET_NAME_QUERY_RESPONSE                     = 0x01004, // 4.3.0 15050
    CMSG_GUILD_QUERY                                 = 0x05C04, // 4.3.0 15050
    SMSG_GUILD_QUERY_RESPONSE                        = 0x01AA4, // 4.3.0 15050
    CMSG_COMMENTATOR_START_WARGAME                   = 0x10020, //
    SMSG_DB_REPLY                                    = 0x10021, //
    SMSG_HOTFIX_NOTIFY_BLOP                          = 0x10022, // sent after SMSG_AUTH_RESPONSE
    SMSG_HOTFIX_NOTIFY                               = 0x10023, // can be sent while ingame
    CMSG_REQUEST_HOTFIX                              = 0x10024, // the client sends this after we send SMSG_HOTFIX_NOTIFY[_BLOP], only sent for the items that the player has in his inventory, that are flagged to be hotfixed
    CMSG_PAGE_TEXT_QUERY                             = 0x07E84, // 4.3.0 15050
    SMSG_PAGE_TEXT_QUERY_RESPONSE                    = 0x07C84, // 4.3.0 15050
    CMSG_QUEST_QUERY                                 = 0x00C26, // 4.3.0 15050
    SMSG_QUEST_QUERY_RESPONSE                        = 0x03880, // 4.3.0 15050
    CMSG_GAMEOBJECT_QUERY                            = 0x06A00, // 4.3.0 15050
    SMSG_GAMEOBJECT_QUERY_RESPONSE                   = 0x04CA6, // 4.3.0 15050
    CMSG_CREATURE_QUERY                              = 0x05EA0, // 4.3.0 15050
    SMSG_CREATURE_QUERY_RESPONSE                     = 0x05086, // 4.3.0 15050
    CMSG_WHO                                         = 0x03226, // 4.3.0 15050
    SMSG_WHO                                         = 0x06006, // 4.3.0 15050
    CMSG_WHOIS                                       = 0x04480, // 4.3.0 15050
    SMSG_WHOIS                                       = 0x02602, // 4.3.0 15050
    CMSG_CONTACT_LIST                                = 0x1002D, //
    SMSG_CONTACT_LIST                                = 0x1002E, //
    SMSG_FRIEND_STATUS                               = 0x1002F, //
    CMSG_ADD_FRIEND                                  = 0x10030, //
    CMSG_DEL_FRIEND                                  = 0x10031, //
    CMSG_SET_CONTACT_NOTES                           = 0x10032, //
    CMSG_ADD_IGNORE                                  = 0x10033, //
    CMSG_DEL_IGNORE                                  = 0x10034, //
    CMSG_GROUP_INVITE                                = 0x10035, //
    SMSG_GROUP_INVITE                                = 0x10036, //
    CMSG_GROUP_CANCEL                                = 0x10037, //
    SMSG_GROUP_CANCEL                                = 0x10038, //
    CMSG_GROUP_ACCEPT                                = 0x10039, //
    CMSG_GROUP_DECLINE                               = 0x1003A, //
    SMSG_GROUP_DECLINE                               = 0x1003B, //
    CMSG_GROUP_UNINVITE                              = 0x1003C, //
    CMSG_GROUP_UNINVITE_GUID                         = 0x1003D, //
    SMSG_GROUP_UNINVITE                              = 0x1003E, //
    CMSG_GROUP_SET_LEADER                            = 0x1003F, //
    SMSG_GROUP_SET_LEADER                            = 0x10040, //
    CMSG_LOOT_METHOD                                 = 0x10041, //
    CMSG_GROUP_DISBAND                               = 0x10042, //
    SMSG_GROUP_DESTROYED                             = 0x10043, //
    SMSG_GROUP_LIST                                  = 0x10044, //
    SMSG_PARTY_MEMBER_STATS                          = 0x10045, //
    SMSG_PARTY_COMMAND_RESULT                        = 0x10046, //
    CMSG_GUILD_CREATE                                = 0x10047, //
    CMSG_GUILD_INVITE                                = 0x10048, //
    SMSG_GUILD_INVITE                                = 0x10049, //
    CMSG_GUILD_ACCEPT                                = 0x1004A, //
    CMSG_GUILD_DECLINE                               = 0x1004B, //
    SMSG_GUILD_DECLINE                               = 0x1004C, //
    CMSG_GUILD_INFO                                  = 0x1004D, //
    SMSG_GUILD_INFO                                  = 0x1004E, //
    CMSG_GUILD_ROSTER                                = 0x1004F, //
    CMSG_REQUEST_GUILD_ROSTER                        = 0x10050, //
    SMSG_GUILD_ROSTER                                = 0x10051, //
    CMSG_GUILD_PROMOTE                               = 0x10052, //
    CMSG_GUILD_DEMOTE                                = 0x10053, //
    CMSG_GUILD_LEAVE                                 = 0x10054, //
    CMSG_GUILD_REMOVE                                = 0x10055, //
    CMSG_GUILD_DISBAND                               = 0x10056, //
    CMSG_GUILD_LEADER                                = 0x10057, //
    CMSG_GUILD_MOTD                                  = 0x10058, //
    CMSG_QUERY_GUILD_REWARDS                         = 0x10059, //
    CMSG_QUERY_GUILD_MAX_XP                          = 0x1005A, //
    CMSG_QUERY_GUILD_XP                              = 0x1005B, //
    SMSG_GUILD_EVENT                                 = 0x1005C, //
    SMSG_GUILD_UPDATE_ROSTER                         = 0x1005D, //
    SMSG_GUILD_RANKS_UPDATE                          = 0x1005E, //
    SMSG_GUILD_REWARDS_LIST                          = 0x1005F, //
    SMSG_GUILD_TRADESKILL_UPDATE                     = 0x10060, //
    SMSG_GUILD_MAX_DAILY_XP                          = 0x10061, //
    SMSG_GUILD_NEWS_UPDATE                           = 0x10062, //
    CMSG_GUILD_REQUEST_NEWS                          = 0x10063, //
    SMSG_GUILD_XP_UPDATE                             = 0x10064, //
    SMSG_GUILD_COMMAND_RESULT                        = 0x10065, //
    CMSG_MESSAGECHAT_SAY                             = 0x10066, //
    CMSG_MESSAGECHAT_YELL                            = 0x10067, //
    CMSG_MESSAGECHAT_CHANNEL                         = 0x10068, //
    CMSG_MESSAGECHAT_WHISPER                         = 0x10069, //
    CMSG_MESSAGECHAT_GUILD                           = 0x1006A, //
    CMSG_MESSAGECHAT_OFFICER                         = 0x1006B, //
    CMSG_MESSAGECHAT_AFK                             = 0x1006C, //
    CMSG_MESSAGECHAT_DND                             = 0x1006D, //
    CMSG_MESSAGECHAT_EMOTE                           = 0x1006E, //
    CMSG_MESSAGECHAT_PARTY                           = 0x1006F, //
    CMSG_MESSAGECHAT_PARTY_LEADER                    = 0x10070, //
    CMSG_MESSAGECHAT_RAID                            = 0x10071, //
    CMSG_MESSAGECHAT_RAID_LEADER                     = 0x10072, //
    CMSG_MESSAGECHAT_BATTLEGROUND                    = 0x10073, //
    CMSG_MESSAGECHAT_BATTLEGROUND_LEADER             = 0x10074, //
    CMSG_MESSAGECHAT_RAID_WARNING                    = 0x10075, //
    SMSG_MESSAGECHAT                                 = 0x10076, //
    CMSG_JOIN_CHANNEL                                = 0x10077, //
    CMSG_LEAVE_CHANNEL                               = 0x10078, //
    SMSG_CHANNEL_NOTIFY                              = 0x10079, //
    CMSG_CHANNEL_LIST                                = 0x1007A, //
    SMSG_CHANNEL_LIST                                = 0x1007B, //
    CMSG_CHANNEL_PASSWORD                            = 0x1007C, //
    CMSG_CHANNEL_SET_OWNER                           = 0x1007D, //
    CMSG_CHANNEL_OWNER                               = 0x1007E, //
    CMSG_CHANNEL_MODERATOR                           = 0x1007F, //
    CMSG_CHANNEL_UNMODERATOR                         = 0x10080, //
    CMSG_CHANNEL_MUTE                                = 0x10081, //
    CMSG_CHANNEL_UNMUTE                              = 0x10082, //
    CMSG_CHANNEL_INVITE                              = 0x10083, //
    CMSG_CHANNEL_KICK                                = 0x10084, //
    CMSG_CHANNEL_ROSTER_INFO                         = 0x10085, //
    CMSG_CHANNEL_BAN                                 = 0x10086, //
    CMSG_CHANNEL_UNBAN                               = 0x10087, //
    CMSG_CHANNEL_ANNOUNCEMENTS                       = 0x10088, //
    CMSG_CHANNEL_MODERATE                            = 0x10089, //
    SMSG_UPDATE_OBJECT                               = 0x04606, // 4.3.0 15050
    SMSG_DESTROY_OBJECT                              = 0x07E80, // 4.3.0 15050
    CMSG_USE_ITEM                                    = 0x1008C, //
    CMSG_OPEN_ITEM                                   = 0x1008D, //
    CMSG_READ_ITEM                                   = 0x1008E, //
    SMSG_READ_ITEM_OK                                = 0x1008F, //
    SMSG_READ_ITEM_FAILED                            = 0x10090, //
    SMSG_ITEM_COOLDOWN                               = 0x10091, //
    CMSG_GAMEOBJ_USE                                 = 0x10092, //
    CMSG_DESTROY_ITEMS                               = 0x10093, //
    SMSG_GAMEOBJECT_CUSTOM_ANIM                      = 0x10094, //
    CMSG_AREATRIGGER                                 = 0x10095, //
    MSG_MOVE_START_FORWARD                           = 0x06683, // 4.3.0 15050
    MSG_MOVE_START_BACKWARD                          = 0x02623, // 4.3.0 15050
    MSG_MOVE_STOP                                    = 0x02483, // 4.3.0 15050
    MSG_MOVE_START_STRAFE_LEFT                       = 0x07021, // 4.3.0 15050
    MSG_MOVE_START_STRAFE_RIGHT                      = 0x02221, // 4.3.0 15050
    MSG_MOVE_STOP_STRAFE                             = 0x076A3, // 4.3.0 15050
    MSG_MOVE_JUMP                                    = 0x03681, // 4.3.0 15050
    MSG_MOVE_START_TURN_LEFT                         = 0x02013, // 4.3.0 15050
    MSG_MOVE_START_TURN_RIGHT                        = 0x03601, // 4.3.0 15050
    MSG_MOVE_STOP_TURN                               = 0x02021, // 4.3.0 15050
    MSG_MOVE_START_PITCH_UP                          = 0x036B1, // 4.3.0 15050
    MSG_MOVE_START_PITCH_DOWN                        = 0x06491, // 4.3.0 15050
    MSG_MOVE_STOP_PITCH                              = 0x07033, // 4.3.0 15050
    MSG_MOVE_SET_RUN_MODE                            = 0x072B1, // 4.3.0 15050
    MSG_MOVE_SET_WALK_MODE                           = 0x10096, //
    MSG_MOVE_TOGGLE_LOGGING                          = 0x10097, //
    MSG_MOVE_TELEPORT                                = 0x0063A, // 4.3.0 15050
    MSG_MOVE_TELEPORT_CHEAT                          = 0x10098, //
    MSG_MOVE_TELEPORT_ACK                            = 0x10099, //
    MSG_MOVE_TOGGLE_FALL_LOGGING                     = 0x1009A, //
    MSG_MOVE_FALL_LAND                               = 0x1009B, //
    MSG_MOVE_START_SWIM                              = 0x02291, // 4.3.0 15050
    MSG_MOVE_STOP_SWIM                               = 0x022B1, // 4.3.0 15050
    MSG_MOVE_SET_RUN_SPEED_CHEAT                     = 0x1009C, //
    MSG_MOVE_SET_RUN_SPEED                           = 0x046A8, // 4.3.0 15050
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                = 0x1009D, //
    MSG_MOVE_SET_RUN_BACK_SPEED                      = 0x02EBC, // 4.3.0 15050
    MSG_MOVE_SET_WALK_SPEED_CHEAT                    = 0x1009E, //
    MSG_MOVE_SET_WALK_SPEED                          = 0x044BC, // 4.3.0 15050
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                    = 0x1009F, //
    MSG_MOVE_SET_SWIM_SPEED                          = 0x04EAA, // 4.3.0 15050
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT               = 0x100A0, //
    MSG_MOVE_SET_SWIM_BACK_SPEED                     = 0x00E1C, // 4.3.0 15050
    MSG_MOVE_SET_ALL_SPEED_CHEAT                     = 0x100A1, //
    MSG_MOVE_SET_TURN_RATE_CHEAT                     = 0x100A2, //
    MSG_MOVE_SET_TURN_RATE                           = 0x100A3, //
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                  = 0x07011, // 4.3.0 15050
    MSG_MOVE_SET_FACING                              = 0x02231, // 4.3.0 15050
    MSG_MOVE_SET_PITCH                               = 0x064A1, // 4.3.0 15050
    MSG_MOVE_WORLDPORT_ACK                           = 0x04334, // 4.3.0 15050
    SMSG_MONSTER_MOVE                                = 0x060A0, // 4.3.0 15050
    SMSG_MOVE_WATER_WALK                             = 0x100A4, //
    SMSG_MOVE_LAND_WALK                              = 0x100A5, //
    MSG_MOVE_SET_RAW_POSITION_ACK                    = 0x100A6, //
    CMSG_MOVE_SET_RAW_POSITION                       = 0x100A7, //
    SMSG_FORCE_RUN_SPEED_CHANGE                      = 0x046A8, // 4.3.0 15050
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                  = 0x060A1, // 4.3.0 15050
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                 = 0x02EBC, // 4.3.0 15050
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK             = 0x100A8, //
    SMSG_FORCE_SWIM_SPEED_CHANGE                     = 0x100A9, //
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                 = 0x100AA, //
    SMSG_FORCE_MOVE_ROOT                             = 0x0461E, // 4.3.0 15050
    CMSG_FORCE_MOVE_ROOT_ACK                         = 0x06031, // 4.3.0 15050
    SMSG_FORCE_MOVE_UNROOT                           = 0x00408, // 4.3.0 15050
    CMSG_FORCE_MOVE_UNROOT_ACK                       = 0x100AB, //
    MSG_MOVE_ROOT                                    = 0x0461E, // 4.3.0 15050
    MSG_MOVE_UNROOT                                  = 0x00408, // 4.3.0 15050
    MSG_MOVE_HEARTBEAT                               = 0x07491, // 4.3.0 15050
    SMSG_MOVE_KNOCK_BACK                             = 0x100AC, //
    CMSG_MOVE_KNOCK_BACK_ACK                         = 0x100AD, //
    MSG_MOVE_KNOCK_BACK                              = 0x100AE, //
    SMSG_MOVE_FEATHER_FALL                           = 0x100AF, //
    SMSG_MOVE_NORMAL_FALL                            = 0x100B0, //
    SMSG_MOVE_SET_HOVER                              = 0x100B1, //
    SMSG_MOVE_UNSET_HOVER                            = 0x100B2, //
    SMSG_MOVE_SET_WALK_IN_AIR                        = 0x100B3, //
    SMSG_MOVE_UNSET_WALK_IN_AIR                      = 0x100B4, //
    CMSG_MOVE_HOVER_ACK                              = 0x100B5, //
    MSG_MOVE_HOVER                                   = 0x100B6, //
    CMSG_TRIGGER_CINEMATIC_CHEAT                     = 0x100B7, //
    CMSG_OPENING_CINEMATIC                           = 0x100B8, //
    SMSG_TRIGGER_CINEMATIC                           = 0x100B9, //
    CMSG_NEXT_CINEMATIC_CAMERA                       = 0x100BA, //
    CMSG_COMPLETE_CINEMATIC                          = 0x100BB, //
    SMSG_TUTORIAL_FLAGS                              = 0x100BC, //
    CMSG_TUTORIAL_FLAG                               = 0x100BD, //
    CMSG_TUTORIAL_CLEAR                              = 0x100BE, //
    CMSG_TUTORIAL_RESET                              = 0x100BF, //
    CMSG_STANDSTATECHANGE                            = 0x100C0, //
    CMSG_EMOTE                                       = 0x100C1, //
    SMSG_EMOTE                                       = 0x100C2, //
    CMSG_TEXT_EMOTE                                  = 0x100C3, //
    SMSG_TEXT_EMOTE                                  = 0x100C4, //
    CMSG_AUTOEQUIP_GROUND_ITEM                       = 0x100C5, //
    CMSG_AUTOSTORE_GROUND_ITEM                       = 0x100C6, //
    CMSG_AUTOSTORE_LOOT_ITEM                         = 0x100C7, //
    CMSG_STORE_LOOT_IN_SLOT                          = 0x100C8, //
    CMSG_AUTOEQUIP_ITEM                              = 0x100C9, //
    CMSG_AUTOSTORE_BAG_ITEM                          = 0x100CA, //
    CMSG_SWAP_ITEM                                   = 0x100CB, //
    CMSG_SWAP_INV_ITEM                               = 0x100CC, //
    CMSG_SPLIT_ITEM                                  = 0x100CD, //
    CMSG_AUTOEQUIP_ITEM_SLOT                         = 0x100CE, //
    OBSOLETE_DROP_ITEM                               = 0x100CF, //
    CMSG_DESTROYITEM                                 = 0x100D0, //
    SMSG_INVENTORY_CHANGE_FAILURE                    = 0x100D1, //
    SMSG_OPEN_CONTAINER                              = 0x100D2, //
    CMSG_INSPECT                                     = 0x100D3, //
    SMSG_INSPECT                                     = 0x100D4, //
    CMSG_INITIATE_TRADE                              = 0x100D5, //
    CMSG_BEGIN_TRADE                                 = 0x100D6, //
    CMSG_BUSY_TRADE                                  = 0x100D7, //
    CMSG_IGNORE_TRADE                                = 0x100D8, //
    CMSG_ACCEPT_TRADE                                = 0x100D9, //
    CMSG_UNACCEPT_TRADE                              = 0x100DA, //
    CMSG_CANCEL_TRADE                                = 0x100DB, //
    CMSG_SET_TRADE_ITEM                              = 0x100DC, //
    CMSG_CLEAR_TRADE_ITEM                            = 0x100DD, //
    CMSG_SET_TRADE_GOLD                              = 0x100DE, //
    SMSG_TRADE_STATUS                                = 0x100DF, //
    SMSG_TRADE_STATUS_EXTENDED                       = 0x100E0, //
    SMSG_INITIALIZE_FACTIONS                         = 0x04E26, // 4.3.0 15050
    SMSG_SET_FACTION_VISIBLE                         = 0x100E2, //
    SMSG_SET_FACTION_STANDING                        = 0x100E3, //
    CMSG_SET_FACTION_ATWAR                           = 0x100E4, //
    CMSG_SET_FACTION_CHEAT                           = 0x100E5, //
    SMSG_SET_PROFICIENCY                             = 0x100E6, //
    CMSG_SET_ACTION_BUTTON                           = 0x100E7, //
    SMSG_ACTION_BUTTONS                              = 0x100E8, //
    SMSG_INITIAL_SPELLS                              = 0x100E9, //
    SMSG_LEARNED_SPELL                               = 0x100EA, //
    SMSG_SUPERCEDED_SPELL                            = 0x100EB, //
    CMSG_NEW_SPELL_SLOT                              = 0x100EC, //
    CMSG_CAST_SPELL                                  = 0x100ED, //
    CMSG_CANCEL_CAST                                 = 0x100EE, //
    SMSG_CAST_FAILED                                 = 0x100EF, //
    SMSG_SPELL_START                                 = 0x100F0, //
    SMSG_SPELL_GO                                    = 0x100F1, //
    SMSG_SPELL_FAILURE                               = 0x100F2, //
    SMSG_SPELL_COOLDOWN                              = 0x100F3, //
    SMSG_COOLDOWN_EVENT                              = 0x100F4, //
    CMSG_CANCEL_AURA                                 = 0x100F5, //
    SMSG_EQUIPMENT_SET_SAVED                         = 0x100F6, //
    SMSG_PET_CAST_FAILED                             = 0x100F7, //
    MSG_CHANNEL_START                                = 0x100F8, //
    MSG_CHANNEL_UPDATE                               = 0x100F9, //
    CMSG_CANCEL_CHANNELLING                          = 0x100FA, //
    SMSG_AI_REACTION                                 = 0x100FB, //
    CMSG_SET_SELECTION                               = 0x100FC, //
    CMSG_EQUIPMENT_SET_DELETE                        = 0x100FD, //
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE              = 0x100FE, //
    CMSG_UNUSED2                                     = 0x100FF, //
    CMSG_ATTACKSWING                                 = 0x10100, //
    CMSG_ATTACKSTOP                                  = 0x10101, //
    SMSG_ATTACKSTART                                 = 0x10102, //
    SMSG_ATTACKSTOP                                  = 0x10103, //
    SMSG_ATTACKSWING_NOTINRANGE                      = 0x10104, //
    SMSG_ATTACKSWING_BADFACING                       = 0x10105, //
    SMSG_INSTANCE_LOCK_WARNING_QUERY                 = 0x10106, //
    SMSG_ATTACKSWING_DEADTARGET                      = 0x10107, //
    SMSG_ATTACKSWING_CANT_ATTACK                     = 0x10108, //
    SMSG_ATTACKERSTATEUPDATE                         = 0x10109, //
    SMSG_BATTLEFIELD_PORT_DENIED                     = 0x1010A, //
    SMSG_DAMAGE_DONE_OBSOLETE                        = 0x1010B, //
    SMSG_UNIT_SPELLCAST_START                        = 0x1010C, //
    SMSG_CANCEL_COMBAT                               = 0x1010D, //
    SMSG_SPELLBREAKLOG                               = 0x1010E, //
    SMSG_SPELLHEALLOG                                = 0x1010F, //
    SMSG_SPELLENERGIZELOG                            = 0x10110, //
    SMSG_BREAK_TARGET                                = 0x10111, //
    CMSG_SAVE_PLAYER                                 = 0x10112, //
    CMSG_SETDEATHBINDPOINT                           = 0x10113, //
    SMSG_BINDPOINTUPDATE                             = 0x10114, //
    CMSG_GETDEATHBINDZONE                            = 0x10115, //
    SMSG_BINDZONEREPLY                               = 0x10116, //
    SMSG_PLAYERBOUND                                 = 0x10117, //
    SMSG_CLIENT_CONTROL_UPDATE                       = 0x07002, // 4.3.0 15050
    CMSG_REPOP_REQUEST                               = 0x06206, // 4.3.0 15050
    SMSG_RESURRECT_REQUEST                           = 0x1011A, //
    CMSG_RESURRECT_RESPONSE                          = 0x1011B, //
    CMSG_LOOT                                        = 0x1011C, //
    CMSG_LOOT_MONEY                                  = 0x1011D, //
    CMSG_LOOT_RELEASE                                = 0x1011E, //
    SMSG_LOOT_RESPONSE                               = 0x1011F, //
    SMSG_LOOT_RELEASE_RESPONSE                       = 0x10120, //
    SMSG_LOOT_REMOVED                                = 0x10121, //
    SMSG_LOOT_MONEY_NOTIFY                           = 0x10122, //
    SMSG_LOOT_ITEM_NOTIFY                            = 0x10123, //
    SMSG_LOOT_CLEAR_MONEY                            = 0x10124, //
    SMSG_ITEM_PUSH_RESULT                            = 0x10125, //
    SMSG_DUEL_REQUESTED                              = 0x10126, //
    SMSG_DUEL_OUTOFBOUNDS                            = 0x10127, //
    SMSG_DUEL_INBOUNDS                               = 0x10128, //
    SMSG_DUEL_COMPLETE                               = 0x10129, //
    SMSG_DUEL_WINNER                                 = 0x1012A, //
    CMSG_DUEL_ACCEPTED                               = 0x03824, // 4.3.0 15050
    CMSG_DUEL_CANCELLED                              = 0x1012B, //
    SMSG_MOUNTRESULT                                 = 0x1012C, //
    SMSG_DISMOUNTRESULT                              = 0x1012D, //
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                = 0x1012E, //
    CMSG_MOUNTSPECIAL_ANIM                           = 0x1012F, //
    SMSG_MOUNTSPECIAL_ANIM                           = 0x10130, //
    SMSG_PET_TAME_FAILURE                            = 0x10131, //
    CMSG_PET_SET_ACTION                              = 0x10132, //
    CMSG_PET_ACTION                                  = 0x10133, //
    CMSG_PET_ABANDON                                 = 0x10134, //
    CMSG_PET_RENAME                                  = 0x10135, //
    SMSG_PET_NAME_INVALID                            = 0x01457, //
    SMSG_PET_SPELLS                                  = 0x10136, //
    SMSG_PET_MODE                                    = 0x10137, //
    CMSG_GOSSIP_HELLO                                = 0x10138, //
    CMSG_GOSSIP_SELECT_OPTION                        = 0x10139, //
    SMSG_GOSSIP_MESSAGE                              = 0x1013A, //
    SMSG_GOSSIP_COMPLETE                             = 0x1013B, //
    CMSG_NPC_TEXT_QUERY                              = 0x03406, // 4.3.0 15050
    SMSG_NPC_TEXT_UPDATE                             = 0x000A0, // 4.3.0 15050
    SMSG_NPC_WONT_TALK                               = 0x1013E, //
    CMSG_QUESTGIVER_STATUS_QUERY                     = 0x1013F, //
    SMSG_QUESTGIVER_STATUS                           = 0x10140, //
    CMSG_QUESTGIVER_HELLO                            = 0x10141, //
    SMSG_QUESTGIVER_QUEST_LIST                       = 0x10142, //
    CMSG_QUESTGIVER_QUERY_QUEST                      = 0x10143, //
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                 = 0x10144, //
    SMSG_QUESTGIVER_QUEST_DETAILS                    = 0x10145, //
    CMSG_QUESTGIVER_ACCEPT_QUEST                     = 0x10146, //
    CMSG_QUESTGIVER_COMPLETE_QUEST                   = 0x10147, //
    SMSG_QUESTGIVER_REQUEST_ITEMS                    = 0x10148, //
    CMSG_QUESTGIVER_REQUEST_REWARD                   = 0x10149, //
    SMSG_QUESTGIVER_OFFER_REWARD                     = 0x1014A, //
    CMSG_QUESTGIVER_CHOOSE_REWARD                    = 0x1014B, //
    SMSG_QUESTGIVER_QUEST_INVALID                    = 0x1014C, //
    CMSG_QUESTGIVER_CANCEL                           = 0x1014D, //
    SMSG_QUESTGIVER_QUEST_COMPLETE                   = 0x1014E, //
    SMSG_QUESTGIVER_QUEST_FAILED                     = 0x1014F, //
    CMSG_QUESTLOG_SWAP_QUEST                         = 0x10150, //
    CMSG_QUESTLOG_REMOVE_QUEST                       = 0x10151, //
    SMSG_QUESTLOG_FULL                               = 0x10152, //
    SMSG_QUESTUPDATE_FAILED                          = 0x10153, //
    SMSG_QUESTUPDATE_FAILEDTIMER                     = 0x10154, //
    SMSG_QUESTUPDATE_COMPLETE                        = 0x10155, //
    SMSG_QUESTUPDATE_ADD_KILL                        = 0x10156, //
    SMSG_QUESTUPDATE_ADD_ITEM                        = 0x10157, //
    CMSG_QUEST_CONFIRM_ACCEPT                        = 0x10158, //
    SMSG_QUEST_CONFIRM_ACCEPT                        = 0x10159, //
    CMSG_PUSHQUESTTOPARTY                            = 0x04624, // 4.3.0 15050
    CMSG_LIST_INVENTORY                              = 0x1015A, //
    SMSG_LIST_INVENTORY                              = 0x1015B, //
    CMSG_SELL_ITEM                                   = 0x1015C, //
    SMSG_SELL_ITEM                                   = 0x1015D, //
    CMSG_BUY_ITEM                                    = 0x1015E, //
    SMSG_BUY_ITEM                                    = 0x1015F, //
    SMSG_BUY_FAILED                                  = 0x10160, //
    CMSG_TAXICLEARALLNODES                           = 0x10161, // Never used
    CMSG_TAXIENABLEALLNODES                          = 0x10162, // Never used
    CMSG_TAXISHOWNODES                               = 0x10163, //
    SMSG_SHOWTAXINODES                               = 0x10164, //
    CMSG_TAXINODE_STATUS_QUERY                       = 0x10165, //
    SMSG_TAXINODE_STATUS                             = 0x10166, //
    CMSG_TAXIQUERYAVAILABLENODES                     = 0x10167, //
    CMSG_ACTIVATETAXI                                = 0x10168, //
    SMSG_ACTIVATETAXIREPLY                           = 0x10169, //
    SMSG_NEW_TAXI_PATH                               = 0x1016A, //
    CMSG_TRAINER_LIST                                = 0x1016B, //
    SMSG_TRAINER_LIST                                = 0x1016C, //
    CMSG_TRAINER_BUY_SPELL                           = 0x1016D, //
    SMSG_TRAINER_BUY_RESULT                          = 0x1016E, //
    CMSG_BINDER_ACTIVATE                             = 0x1016F, //
    SMSG_PLAYERBINDERROR                             = 0x10170, //
    CMSG_BANKER_ACTIVATE                             = 0x10171, //
    SMSG_SHOW_BANK                                   = 0x10172, //
    CMSG_BUY_BANK_SLOT                               = 0x10173, //
    SMSG_BUY_BANK_SLOT_RESULT                        = 0x10174, //
    CMSG_PETITION_SHOWLIST                           = 0x10175, //
    SMSG_PETITION_SHOWLIST                           = 0x10176, //
    CMSG_PETITION_BUY                                = 0x10177, //
    CMSG_PETITION_SHOW_SIGNATURES                    = 0x10178, //
    SMSG_PETITION_SHOW_SIGNATURES                    = 0x10179, //
    CMSG_PETITION_SIGN                               = 0x1017A, //
    SMSG_PETITION_SIGN_RESULTS                       = 0x1017B, //
    MSG_PETITION_DECLINE                             = 0x1017C, //
    CMSG_OFFER_PETITION                              = 0x1017D, //
    CMSG_TURN_IN_PETITION                            = 0x1017E, //
    SMSG_TURN_IN_PETITION_RESULTS                    = 0x1017F, //
    CMSG_PETITION_QUERY                              = 0x07880, // 4.3.0 15050
    SMSG_PETITION_QUERY_RESPONSE                     = 0x01C02, // 4.3.0 15050
    SMSG_FISH_NOT_HOOKED                             = 0x10182, //
    SMSG_FISH_ESCAPED                                = 0x10183, //
    CMSG_BUG                                         = 0x10184, //
    SMSG_NOTIFICATION                                = 0x10185, //
    CMSG_PLAYED_TIME                                 = 0x10186, //
    SMSG_PLAYED_TIME                                 = 0x10187, //
    CMSG_QUERY_TIME                                  = 0x10188, //
    SMSG_QUERY_TIME_RESPONSE                         = 0x10189, //
    SMSG_LOG_XPGAIN                                  = 0x1018A, //
    SMSG_AURACASTLOG                                 = 0x1018B, //
    CMSG_RECLAIM_CORPSE                              = 0x1018C, //
    CMSG_WRAP_ITEM                                   = 0x1018D, //
    SMSG_LEVELUP_INFO                                = 0x1018E, //
    MSG_MINIMAP_PING                                 = 0x1018F, //
    SMSG_RESISTLOG                                   = 0x10190, //
    SMSG_ENCHANTMENTLOG                              = 0x10191, //
    CMSG_SET_SKILL_CHEAT                             = 0x10192, //
    SMSG_START_MIRROR_TIMER                          = 0x10193, //
    SMSG_PAUSE_MIRROR_TIMER                          = 0x10194, //
    SMSG_STOP_MIRROR_TIMER                           = 0x10195, //
    CMSG_PING                                        = 0x00100, // 4.3.0 15050
    SMSG_PONG                                        = 0x00302, // 4.3.0 15050
    SMSG_CLEAR_COOLDOWN                              = 0x10196, //
    SMSG_GAMEOBJECT_PAGETEXT                         = 0x10197, //
    CMSG_SETSHEATHED                                 = 0x10198, //
    SMSG_COOLDOWN_CHEAT                              = 0x10199, //
    SMSG_SPELL_DELAYED                               = 0x1019A, //
    CMSG_QUEST_POI_QUERY                             = 0x1019B, //
    SMSG_QUEST_POI_QUERY_RESPONSE                    = 0x1019C, //
    CMSG_GHOST                                       = 0x1019D, //
    CMSG_GM_INVIS                                    = 0x1019E, //
    SMSG_INVALID_PROMOTION_CODE                      = 0x1019F, //
    MSG_GM_BIND_OTHER                                = 0x101A0, //
    MSG_GM_SUMMON                                    = 0x101A1, //
    SMSG_ITEM_TIME_UPDATE                            = 0x101A2, //
    SMSG_ITEM_ENCHANT_TIME_UPDATE                    = 0x101A3, //
    SMSG_AUTH_CHALLENGE                              = 0x01723, // 4.3.0 15050
    CMSG_AUTH_SESSION                                = 0x01100, // 4.3.0 15050
    SMSG_AUTH_RESPONSE                               = 0x01406, // 4.3.0 15050
    MSG_GM_SHOWLABEL                                 = 0x101A4, //
    CMSG_PET_CAST_SPELL                              = 0x101A5, //
    MSG_SAVE_GUILD_EMBLEM                            = 0x101A6, //
    MSG_TABARDVENDOR_ACTIVATE                        = 0x101A7, //
    SMSG_PLAY_SPELL_VISUAL                           = 0x101A8, //
    CMSG_ZONEUPDATE                                  = 0x03600, // 4.3.0 15050
    SMSG_PARTYKILLLOG                                = 0x101AA, //
    SMSG_COMPRESSED_UPDATE_OBJECT                    = 0x101AB, //
    SMSG_PLAY_SPELL_IMPACT                           = 0x101AC, //
    SMSG_EXPLORATION_EXPERIENCE                      = 0x101AD, //
    CMSG_GM_SET_SECURITY_GROUP                       = 0x101AE, //
    CMSG_GM_NUKE                                     = 0x101AF, //
    MSG_RANDOM_ROLL                                  = 0x101B0, //
    SMSG_ENVIRONMENTALDAMAGELOG                      = 0x101B1, //
    CMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x101B2, //
    SMSG_RWHOIS                                      = 0x101B3, //
    SMSG_LFG_PLAYER_REWARD                           = 0x101B4, //
    SMSG_LFG_TELEPORT_DENIED                         = 0x101B5, //
    CMSG_UNLEARN_SPELL                               = 0x101B6, //
    CMSG_UNLEARN_SKILL                               = 0x101B7, //
    SMSG_REMOVED_SPELL                               = 0x101B8, //
    CMSG_DECHARGE                                    = 0x101B9, //
    CMSG_GMTICKET_CREATE                             = 0x101BA, //
    SMSG_GMTICKET_CREATE                             = 0x101BB, //
    CMSG_GMTICKET_UPDATETEXT                         = 0x101BC, //
    SMSG_GMTICKET_UPDATETEXT                         = 0x101BD, //
    SMSG_ACCOUNT_DATA_TIMES                          = 0x00C80, // 4.3.0 15050
    CMSG_REQUEST_ACCOUNT_DATA                        = 0x04002, // 4.3.0 15050
    CMSG_UPDATE_ACCOUNT_DATA                         = 0x002A0, // 4.3.0 15050
    SMSG_UPDATE_ACCOUNT_DATA                         = 0x01EA3, // 4.3.0 15050
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                   = 0x101C0, //
    SMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x101C1, //
    CMSG_GM_TEACH                                    = 0x101C2, //
    CMSG_GM_CREATE_ITEM_TARGET                       = 0x101C3, //
    CMSG_GMTICKET_GETTICKET                          = 0x101C4, //
    SMSG_GMTICKET_GETTICKET                          = 0x101C5, //
    CMSG_UNLEARN_TALENTS                             = 0x101C6, //
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT              = 0x101C7, // wtf::SMSG_GAMEOBJECT_SPAWN_ANIM_OBSOLETE
    SMSG_GAMEOBJECT_DESPAWN_ANIM                     = 0x101C8, //
    MSG_CORPSE_QUERY                                 = 0x101C9, //
    CMSG_GMTICKET_DELETETICKET                       = 0x101CA, //
    SMSG_GMTICKET_DELETETICKET                       = 0x101CB, //
    SMSG_CHAT_WRONG_FACTION                          = 0x101CC, //
    CMSG_GMTICKET_SYSTEMSTATUS                       = 0x101CD, //
    SMSG_GMTICKET_SYSTEMSTATUS                       = 0x101CE, //
    CMSG_SPIRIT_HEALER_ACTIVATE                      = 0x101CF, //
    SMSG_QUEST_FORCE_REMOVED                         = 0x101D0, //
    CMSG_SKILL_BUY_STEP                              = 0x101D1, //
    CMSG_SKILL_BUY_RANK                              = 0x101D2, //
    SMSG_SPIRIT_HEALER_CONFIRM                       = 0x101D3, //
    CMSG_CHARACTER_POINT_CHEAT                       = 0x101D4, //
    SMSG_GOSSIP_POI                                  = 0x101D5, //
    CMSG_CHAT_IGNORED                                = 0x101D6, //
    CMSG_GUILD_RANK                                  = 0x101D7, //
    SMSG_GUILD_RANK                                  = 0x101D8, //
    CMSG_GUILD_RANKS                                 = 0x101D9, //
    CMSG_GUILD_ADD_RANK                              = 0x101DA, //
    CMSG_GUILD_DEL_RANK                              = 0x101DB, //
    CMSG_GUILD_SWITCH_RANK                           = 0x101DC, //
    CMSG_GUILD_SET_NOTE                              = 0x101DD, //
    CMSG_GUILD_QUERY_TRADESKILL                      = 0x101DE, //
    SMSG_LOGIN_VERIFY_WORLD                          = 0x01C80, // 4.3.0 15050
    CMSG_CLEAR_EXPLORATION                           = 0x101DE, //
    CMSG_SEND_MAIL                                   = 0x101DF, //
    SMSG_SEND_MAIL_RESULT                            = 0x101F0, //
    CMSG_GET_MAIL_LIST                               = 0x101F1, //
    SMSG_MAIL_LIST_RESULT                            = 0x101F2, //
    CMSG_BATTLEFIELD_LIST                            = 0x101F3, //
    SMSG_BATTLEFIELD_LIST                            = 0x101F4, //
    CMSG_BATTLEFIELD_JOIN                            = 0x101F5, //
    SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x101F6, //
    CMSG_REQUEST_RATED_BG_INFO                       = 0x101F7, //
    CMSG_REQUEST_PVP_OPTIONS_ENABLED                 = 0x101F8, //
    CMSG_JOIN_RATED_BATTLEFIELD                      = 0x101F9, //
    CMSG_ITEM_TEXT_QUERY                             = 0x101FA, //
    SMSG_ITEM_TEXT_QUERY_RESPONSE                    = 0x101FB, //
    CMSG_MAIL_TAKE_MONEY                             = 0x101FC, //
    CMSG_MAIL_TAKE_ITEM                              = 0x101FD, //
    CMSG_MAIL_MARK_AS_READ                           = 0x101FE, //
    CMSG_MAIL_RETURN_TO_SENDER                       = 0x101FF, //
    CMSG_MAIL_DELETE                                 = 0x10200, //
    CMSG_MAIL_CREATE_TEXT_ITEM                       = 0x10201, //
    SMSG_SPELLLOGMISS                                = 0x10202, //
    SMSG_SPELLLOGEXECUTE                             = 0x10203, //
    SMSG_DEBUGAURAPROC                               = 0x10204, //
    SMSG_PERIODICAURALOG                             = 0x10205, //
    SMSG_SPELLDAMAGESHIELD                           = 0x10206, //
    SMSG_SPELLNONMELEEDAMAGELOG                      = 0x10207, //
    CMSG_LEARN_TALENT                                = 0x10208, //
    SMSG_RESURRECT_FAILED                            = 0x0D557, //
    CMSG_TOGGLE_PVP                                  = 0x10209, //
    SMSG_ZONE_UNDER_ATTACK                           = 0x1020A, //
    MSG_AUCTION_HELLO                                = 0x1020B, //
    CMSG_AUCTION_SELL_ITEM                           = 0x1020C, //
    CMSG_AUCTION_REMOVE_ITEM                         = 0x1020D, //
    CMSG_AUCTION_LIST_ITEMS                          = 0x1020E, //
    CMSG_AUCTION_LIST_OWNER_ITEMS                    = 0x1020F, //
    CMSG_AUCTION_PLACE_BID                           = 0x10210, //
    SMSG_AUCTION_COMMAND_RESULT                      = 0x10211, //
    SMSG_AUCTION_LIST_RESULT                         = 0x10212, //
    SMSG_AUCTION_OWNER_LIST_RESULT                   = 0x10213, //
    SMSG_AUCTION_BIDDER_NOTIFICATION                 = 0x10214, //
    SMSG_AUCTION_OWNER_NOTIFICATION                  = 0x10215, //
    SMSG_PROCRESIST                                  = 0x10216, //
    SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE          = 0x10217, //
    SMSG_DISPEL_FAILED                               = 0x10218, //
    SMSG_SPELLORDAMAGE_IMMUNE                        = 0x10219, //
    CMSG_AUCTION_LIST_BIDDER_ITEMS                   = 0x1021A, //
    SMSG_AUCTION_BIDDER_LIST_RESULT                  = 0x1021B, //
    SMSG_SET_FLAT_SPELL_MODIFIER                     = 0x1021C, //
    SMSG_SET_PCT_SPELL_MODIFIER                      = 0x1021D, //
    CMSG_SET_AMMO                                    = 0x1021E, //
    SMSG_CORPSE_RECLAIM_DELAY                        = 0x1021F, //
    CMSG_SET_ACTIVE_MOVER                            = 0x10220, //
    CMSG_PET_CANCEL_AURA                             = 0x10221, //
    CMSG_PLAYER_AI_CHEAT                             = 0x10222, //
    CMSG_CANCEL_AUTO_REPEAT_SPELL                    = 0x10223, //
    MSG_GM_ACCOUNT_ONLINE                            = 0x10224, //
    MSG_LIST_STABLED_PETS                            = 0x10225, //
    SMSG_STABLE_RESULT                               = 0x10226, //
    CMSG_STABLE_REVIVE_PET                           = 0x10227, //
    CMSG_STABLE_CHANGE_SLOT                          = 0x10228, //
    MSG_QUEST_PUSH_RESULT                            = 0x10229, //
    SMSG_PLAY_MUSIC                                  = 0x1022A, //
    SMSG_PLAY_OBJECT_SOUND                           = 0x1022B, //
    CMSG_REQUEST_PET_INFO                            = 0x1022C, //
    CMSG_FAR_SIGHT                                   = 0x1022D, //
    SMSG_SPELLDISPELLOG                              = 0x1022E,  //
    SMSG_DAMAGE_CALC_LOG                             = 0x1022F, //
    CMSG_ENABLE_DAMAGE_LOG                           = 0x10230, //
    CMSG_GROUP_CHANGE_SUB_GROUP                      = 0x10231, //
    CMSG_REQUEST_PARTY_MEMBER_STATS                  = 0x10232, //
    CMSG_GROUP_SWAP_SUB_GROUP                        = 0x10233, //
    CMSG_RESET_FACTION_CHEAT                         = 0x10234, //
    CMSG_AUTOSTORE_BANK_ITEM                         = 0x10235, //
    CMSG_AUTOBANK_ITEM                               = 0x10236, //
    MSG_QUERY_NEXT_MAIL_TIME                         = 0x10237, //
    SMSG_RECEIVED_MAIL                               = 0x10238, //
    SMSG_RAID_GROUP_ONLY                             = 0x00554, //
    CMSG_SET_DURABILITY_CHEAT                        = 0x10239, //
    CMSG_SET_PVP_RANK_CHEAT                          = 0x1023A, //
    CMSG_ADD_PVP_MEDAL_CHEAT                         = 0x1023B, //
    CMSG_DEL_PVP_MEDAL_CHEAT                         = 0x1023C, //
    CMSG_SET_PVP_TITLE                               = 0x1023D, //
    SMSG_PVP_CREDIT                                  = 0x1023E, //
    SMSG_AUCTION_REMOVED_NOTIFICATION                = 0x1023F, //
    CMSG_GROUP_RAID_CONVERT                          = 0x10240, //
    CMSG_GROUP_ASSISTANT_LEADER                      = 0x10241, //
    CMSG_BUYBACK_ITEM                                = 0x10242, //
    SMSG_SERVER_MESSAGE                              = 0x10243, //
    CMSG_SET_SAVED_INSTANCE_EXTEND                   = 0x10244, //
    SMSG_LFG_OFFER_CONTINUE                          = 0x10245, //
    CMSG_MEETINGSTONE_CHEAT                          = 0x10246, //
    SMSG_MEETINGSTONE_SETQUEUE                       = 0x10247, //
    CMSG_MEETINGSTONE_INFO                           = 0x10248, //
    SMSG_MEETINGSTONE_COMPLETE                       = 0x10249, //
    SMSG_MEETINGSTONE_IN_PROGRESS                    = 0x1024A, //
    SMSG_MEETINGSTONE_MEMBER_ADDED                   = 0x1024B, //
    CMSG_GMTICKETSYSTEM_TOGGLE                       = 0x1024C, //
    CMSG_CANCEL_GROWTH_AURA                          = 0x1024D, //
    SMSG_CANCEL_AUTO_REPEAT                          = 0x1024E, //
    SMSG_STANDSTATE_UPDATE                           = 0x1024F, //
    SMSG_LOOT_ALL_PASSED                             = 0x10250, //
    SMSG_LOOT_ROLL_WON                               = 0x10251, //
    CMSG_LOOT_ROLL                                   = 0x10252, //
    SMSG_LOOT_START_ROLL                             = 0x10253, //
    SMSG_LOOT_ROLL                                   = 0x10254, //
    CMSG_LOOT_MASTER_GIVE                            = 0x10255, //
    SMSG_LOOT_MASTER_LIST                            = 0x10256, //
    SMSG_SET_FORCED_REACTIONS                        = 0x10257, //
    SMSG_SPELL_FAILED_OTHER                          = 0x10258, //
    SMSG_GAMEOBJECT_RESET_STATE                      = 0x10259, //
    CMSG_REPAIR_ITEM                                 = 0x1025A, //
    SMSG_CHAT_PLAYER_NOT_FOUND                       = 0x1025B, //
    MSG_TALENT_WIPE_CONFIRM                          = 0x1025C, //
    SMSG_SUMMON_REQUEST                              = 0x1025D, //
    CMSG_SUMMON_RESPONSE                             = 0x1025E, //
    MSG_MOVE_TOGGLE_GRAVITY_CHEAT                    = 0x1025F, //
    SMSG_MONSTER_MOVE_TRANSPORT                      = 0x10260, //
    SMSG_PET_BROKEN                                  = 0x10261, //
    MSG_MOVE_FEATHER_FALL                            = 0x10262, //
    MSG_MOVE_WATER_WALK                              = 0x10263, //
    CMSG_SERVER_BROADCAST                            = 0x10264, //
    CMSG_SELF_RES                                    = 0x10265, //
    SMSG_FEIGN_DEATH_RESISTED                        = 0x10266, //
    CMSG_RUN_SCRIPT                                  = 0x10267, //
    SMSG_SCRIPT_MESSAGE                              = 0x10268, //
    SMSG_DUEL_COUNTDOWN                              = 0x10269, //
    SMSG_AREA_TRIGGER_MESSAGE                        = 0x1026A, //
    CMSG_SHOWING_HELM                                = 0x1026B, //
    CMSG_SHOWING_CLOAK                               = 0x1026C, //
    SMSG_LFG_ROLE_CHOSEN                             = 0x1026D, //
    SMSG_PLAYER_SKINNED                              = 0x1026E, //
    SMSG_DURABILITY_DAMAGE_DEATH                     = 0x1026F, //
    CMSG_SET_EXPLORATION                             = 0x10270, //
    CMSG_SET_ACTIONBAR_TOGGLES                       = 0x10271, //
    MSG_PETITION_RENAME                              = 0x10272, //
    SMSG_INIT_WORLD_STATES                           = 0x10273, //
    SMSG_UPDATE_WORLD_STATE                          = 0x10274, //
    CMSG_ITEM_NAME_QUERY                             = 0x10275, //
    SMSG_ITEM_NAME_QUERY_RESPONSE                    = 0x10276, //
    SMSG_PET_ACTION_FEEDBACK                         = 0x10277, //
    CMSG_CHAR_RENAME                                 = 0x10278, //
    SMSG_CHAR_RENAME                                 = 0x10279, //
    CMSG_MOVE_SPLINE_DONE                            = 0x1027A, //
    CMSG_MOVE_FALL_RESET                             = 0x1027B, //
    SMSG_INSTANCE_SAVE_CREATED                       = 0x1027C, //
    SMSG_RAID_INSTANCE_INFO                          = 0x1027D, //
    CMSG_REQUEST_RAID_INFO                           = 0x1027E, //
    CMSG_MOVE_TIME_SKIPPED                           = 0x1027F, //
    CMSG_MOVE_FEATHER_FALL_ACK                       = 0x10280, //
    CMSG_MOVE_WATER_WALK_ACK                         = 0x10281, //
    CMSG_MOVE_NOT_ACTIVE_MOVER                       = 0x10282, //
    SMSG_PLAY_SOUND                                  = 0x10283, //
    CMSG_BATTLEFIELD_STATUS                          = 0x10284, //
    SMSG_BATTLEFIELD_STATUS1                         = 0x10285, //
    SMSG_BATTLEFIELD_STATUS2                         = 0x10286, //
    SMSG_BATTLEFIELD_STATUS3                         = 0x10287, //
    SMSG_BATTLEFIELD_STATUS4                         = 0x10288, //
    CMSG_BATTLEFIELD_PORT                            = 0x10289, //
    CMSG_INSPECT_HONOR_STATS                         = 0x1028A, //
    SMSG_INSPECT_HONOR_STATS                         = 0x1028B, //
    CMSG_BATTLEMASTER_HELLO                          = 0x06D57, //
    CMSG_MOVE_START_SWIM_CHEAT                       = 0x1028C, //
    CMSG_MOVE_STOP_SWIM_CHEAT                        = 0x1028D, //
    SMSG_FORCE_WALK_SPEED_CHANGE                     = 0x1028E, //
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                 = 0x1028F, //
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE                = 0x10290, //
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK            = 0x10291, //
    SMSG_FORCE_TURN_RATE_CHANGE                      = 0x10292, //
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                  = 0x10293, //
    MSG_PVP_LOG_DATA                                 = 0x10294, //
    SMSG_PVP_RATED_STATS_UPDATE                      = 0x10295, //
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA              = 0x10296, //
    CMSG_LEAVE_BATTLEFIELD                           = 0x10297, //
    CMSG_AREA_SPIRIT_HEALER_QUERY                    = 0x10298, //
    CMSG_AREA_SPIRIT_HEALER_QUEUE                    = 0x10299, //
    SMSG_AREA_SPIRIT_HEALER_TIME                     = 0x1029A, //
    CMSG_GM_UNTEACH                                  = 0x1029B, //
    SMSG_WARDEN_DATA                                 = 0x004BE, // 4.3.0 15050
    CMSG_WARDEN_DATA                                 = 0x04934, // 4.3.0 15050
    SMSG_GROUP_JOINED_BATTLEGROUND                   = 0x1029D, //
    CMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x1029E, //
    SMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x1029F, //
    CMSG_PET_STOP_ATTACK                             = 0x10300, //
    SMSG_BINDER_CONFIRM                              = 0x10301, //
    SMSG_BATTLEGROUND_PLAYER_JOINED                  = 0x10302, //
    SMSG_BATTLEGROUND_PLAYER_LEFT                    = 0x10303, //
    CMSG_BATTLEMASTER_JOIN                           = 0x10304, //
    SMSG_ADDON_INFO                                  = 0x004A0, // 4.3.0 15050
    CMSG_PET_UNLEARN                                 = 0x10305, //
    SMSG_PET_UNLEARN_CONFIRM                         = 0x10306, //
    SMSG_PARTY_MEMBER_STATS_FULL                     = 0x10307, //
    CMSG_PET_SPELL_AUTOCAST                          = 0x10308, //
    SMSG_WEATHER                                     = 0x10309, //
    SMSG_PLAY_TIME_WARNING                           = 0x1030A, //
    SMSG_MINIGAME_SETUP                              = 0x1030B, //
    SMSG_MINIGAME_STATE                              = 0x1030C, //
    CMSG_MINIGAME_MOVE                               = 0x1030D, //
    SMSG_MINIGAME_MOVE_FAILED                        = 0x1030E, //
    SMSG_RAID_INSTANCE_MESSAGE                       = 0x1030F, //
    SMSG_COMPRESSED_MOVES                            = 0x10310, //
    CMSG_GUILD_INFO_TEXT                             = 0x10311, //
    SMSG_GUILD_PARTY_STATE_UPDATE                    = 0x10312, // structure: uint8(isGuildGroup << 7) uint32(numGuildRequired) uint32(numGuildPresent) float(xpMultiplier) NOTE: xpMultiplier/100.0f
    SMSG_CHAT_RESTRICTED                             = 0x10313, //
    SMSG_SPLINE_SET_RUN_SPEED                        = 0x10314, //
    SMSG_SPLINE_SET_RUN_BACK_SPEED                   = 0x10315, //
    SMSG_SPLINE_SET_SWIM_SPEED                       = 0x10316, //
    SMSG_SPLINE_SET_WALK_SPEED                       = 0x10317, //
    SMSG_SPLINE_SET_SWIM_BACK_SPEED                  = 0x10318, //
    SMSG_SPLINE_SET_TURN_RATE                        = 0x10319, //
    SMSG_SPLINE_MOVE_UNROOT                          = 0x1031A, //
    SMSG_SPLINE_MOVE_FEATHER_FALL                    = 0x1031B, //
    SMSG_SPLINE_MOVE_NORMAL_FALL                     = 0x1031C, //
    SMSG_SPLINE_MOVE_SET_HOVER                       = 0x1031D, //
    SMSG_SPLINE_MOVE_UNSET_HOVER                     = 0x1031E, //
    SMSG_SPLINE_MOVE_WATER_WALK                      = 0x1031F, //
    SMSG_SPLINE_MOVE_LAND_WALK                       = 0x10320, //
    SMSG_SPLINE_MOVE_START_SWIM                      = 0x10321, //
    SMSG_SPLINE_MOVE_STOP_SWIM                       = 0x10322, //
    SMSG_SPLINE_MOVE_SET_RUN_MODE                    = 0x10323, //
    SMSG_SPLINE_MOVE_SET_WALK_MODE                   = 0x10324, //
    CMSG_GM_NUKE_ACCOUNT                             = 0x10325, //
    MSG_GM_DESTROY_CORPSE                            = 0x10326, //
    CMSG_GM_DESTROY_ONLINE_CORPSE                    = 0x10327, //
    CMSG_ACTIVATETAXIEXPRESS                         = 0x10328, //
    SMSG_SET_FACTION_ATWAR                           = 0x10329, //
    SMSG_GAMETIMEBIAS_SET                            = 0x1032A, //
    CMSG_DEBUG_ACTIONS_START                         = 0x1032B, //
    CMSG_DEBUG_ACTIONS_STOP                          = 0x1032C, //
    CMSG_SET_FACTION_INACTIVE                        = 0x1032D, //
    CMSG_SET_WATCHED_FACTION                         = 0x1032E, //
    MSG_MOVE_TIME_SKIPPED                            = 0x1032F, //
    SMSG_SPLINE_MOVE_ROOT                            = 0x10330, //
    CMSG_SET_EXPLORATION_ALL                         = 0x10331, //
    SMSG_INVALIDATE_PLAYER                           = 0x10332, //
    CMSG_RESET_INSTANCES                             = 0x10333, //
    SMSG_INSTANCE_RESET                              = 0x10334, //
    SMSG_INSTANCE_RESET_FAILED                       = 0x10335, //
    SMSG_UPDATE_LAST_INSTANCE                        = 0x10336, //
    MSG_RAID_TARGET_UPDATE                           = 0x10337, //
    MSG_RAID_READY_CHECK                             = 0x10338, //
    SMSG_RAID_READY_CHECK_THROTTLED                  = 0x10339, //
    CMSG_LUA_USAGE                                   = 0x1033A, //
    SMSG_PET_ACTION_SOUND                            = 0x1033B, //
    SMSG_PET_DISMISS_SOUND                           = 0x1033C, //
    SMSG_GHOSTEE_GONE                                = 0x1033D, //
    CMSG_GM_UPDATE_TICKET_STATUS                     = 0x1033E, //
    SMSG_GM_TICKET_STATUS_UPDATE                     = 0x1033F, //
    MSG_SET_DUNGEON_DIFFICULTY                       = 0x10340, //
    CMSG_GMSURVEY_SUBMIT                             = 0x10341, //
    SMSG_UPDATE_INSTANCE_OWNERSHIP                   = 0x10342, //
    CMSG_IGNORE_KNOCKBACK_CHEAT                      = 0x10343, //
    SMSG_CHAT_PLAYER_AMBIGUOUS                       = 0x10344, //
    MSG_DELAY_GHOST_TELEPORT                         = 0x10345, //
    SMSG_SPELLINSTAKILLLOG                           = 0x10346, //
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                  = 0x10347, //
    CMSG_CHAT_FILTERED                               = 0x10348, //
    SMSG_EXPECTED_SPAM_RECORDS                       = 0x10349, //
    SMSG_SPELLSTEALLOG                               = 0x1034A, //
    CMSG_LOTTERY_QUERY_OBSOLETE                      = 0x1034B, //
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE               = 0x1034C, //
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE                 = 0x1034D, //
    SMSG_LOTTERY_RESULT_OBSOLETE                     = 0x1034E, //
    SMSG_CHARACTER_PROFILE                           = 0x1034F, //
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED           = 0x10350, //
    SMSG_DEFENSE_MESSAGE                             = 0x10351, //
    SMSG_INSTANCE_DIFFICULTY                         = 0x10352, //
    MSG_GM_RESETINSTANCELIMIT                        = 0x10353, //
    SMSG_MOTD                                        = 0x10354, //
    SMSG_MOVE_SET_FLIGHT                             = 0x10355, //
    SMSG_MOVE_UNSET_FLIGHT                           = 0x10356, //
    CMSG_MOVE_FLIGHT_ACK                             = 0x10357, //
    MSG_MOVE_START_SWIM_CHEAT                        = 0x10358, //
    MSG_MOVE_STOP_SWIM_CHEAT                         = 0x10359, //
    SMSG_MOVE_SET_CAN_FLY                            = 0x1035A, //
    SMSG_MOVE_UNSET_CAN_FLY                          = 0x1035B, //
    CMSG_MOVE_SET_CAN_FLY_ACK                        = 0x1035C, //
    CMSG_MOVE_SET_FLY                                = 0x1035D, //
    CMSG_SOCKET_GEMS                                 = 0x1035E, //
    CMSG_ARENA_TEAM_CREATE                           = 0x1035F, //
    SMSG_ARENA_TEAM_COMMAND_RESULT                   = 0x10360, //
    CMSG_ARENA_TEAM_QUERY                            = 0x10361, //
    SMSG_ARENA_TEAM_QUERY_RESPONSE                   = 0x10362, //
    CMSG_ARENA_TEAM_ROSTER                           = 0x10363, //
    SMSG_ARENA_TEAM_ROSTER                           = 0x10364, //
    CMSG_ARENA_TEAM_INVITE                           = 0x10365, //
    SMSG_ARENA_TEAM_INVITE                           = 0x10366, //
    CMSG_ARENA_TEAM_ACCEPT                           = 0x10367, //
    CMSG_ARENA_TEAM_DECLINE                          = 0x10368, //
    CMSG_ARENA_TEAM_LEAVE                            = 0x10369, //
    CMSG_ARENA_TEAM_REMOVE                           = 0x1036A, //
    CMSG_ARENA_TEAM_DISBAND                          = 0x1036B, //
    CMSG_ARENA_TEAM_LEADER                           = 0x1036C, //
    SMSG_ARENA_TEAM_EVENT                            = 0x1036D, //
    CMSG_BATTLEMASTER_JOIN_ARENA                     = 0x1036E, //
    MSG_MOVE_START_ASCEND                            = 0x1036F, //
    MSG_MOVE_STOP_ASCEND                             = 0x10370, //
    SMSG_ARENA_TEAM_STATS                            = 0x10371, //
    CMSG_LFG_JOIN                                    = 0x10372, //
    CMSG_LFG_LEAVE                                   = 0x10373, //
    CMSG_SEARCH_LFG_JOIN                             = 0x10374, //
    CMSG_SEARCH_LFG_LEAVE                            = 0x10375, //
    SMSG_UPDATE_LFG_LIST                             = 0x10376, //
    SMSG_LFG_PROPOSAL_UPDATE                         = 0x10377, //
    CMSG_LFG_PROPOSAL_RESULT                         = 0x10378, //
    SMSG_LFG_ROLE_CHECK_UPDATE                       = 0x10379, //
    SMSG_RAID_ROLE_CHECK_UPDATE                      = 0x1037A, //
    SMSG_LFG_JOIN_RESULT                             = 0x1037B, //
    SMSG_LFG_QUEUE_STATUS                            = 0x1037C, //
    CMSG_SET_LFG_COMMENT                             = 0x1037D, //
    SMSG_LFG_UPDATE_PLAYER                           = 0x1037E, //
    SMSG_LFG_UPDATE_PARTY                            = 0x1037F, //
    SMSG_LFG_UPDATE_LIST                             = 0x10380, //
    CMSG_LFG_SET_ROLES                               = 0x10381, //
    CMSG_LFG_SET_NEEDS                               = 0x10382, //
    CMSG_LFG_SET_BOOT_VOTE                           = 0x10383, //
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                    = 0x10384, //
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST                = 0x10385, //
    SMSG_LFG_PLAYER_INFO                             = 0x10386, //
    //SMSG_LFG_PLAYER_INFO                             = 0x10387, // :redefinition; previous def was 'enumerator'
    CMSG_LFG_TELEPORT                                = 0x10388, //
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                 = 0x10389, //
    SMSG_LFG_PARTY_INFO                              = 0x1038A, //
    SMSG_TITLE_EARNED                                = 0x1038B, //
    CMSG_SET_TITLE                                   = 0x1038C, //
    CMSG_CANCEL_MOUNT_AURA                           = 0x1038D, //  not sure
    SMSG_ARENA_ERROR                                 = 0x1038E, //
    MSG_INSPECT_ARENA_TEAMS                          = 0x1038F, //
    SMSG_DEATH_RELEASE_LOC                           = 0x10390, //
    CMSG_CANCEL_TEMP_ENCHANTMENT                     = 0x10391, //
    SMSG_FORCED_DEATH_UPDATE                         = 0x10392, //
    CMSG_CHEAT_SET_HONOR_CURRENCY                    = 0x10393, //
    CMSG_CHEAT_SET_ARENA_CURRENCY                    = 0x10394, //
    SMSG_INIT_CURRENCY                               = 0x10395, //
    SMSG_UPDATE_CURRENCY                             = 0x10396, //
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                  = 0x10397, //
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                  = 0x10398, //
    MSG_MOVE_SET_FLIGHT_SPEED                        = 0x10399, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT             = 0x1039A, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0x1039B, //
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                   = 0x1039C, //
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK               = 0x1039D, //
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE              = 0x1039E, //
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK          = 0x1039F, //
    SMSG_SPLINE_SET_FLIGHT_SPEED                     = 0x103A0, //
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED                = 0x103A1, //
    CMSG_MAELSTROM_INVALIDATE_CACHE                  = 0x103A2, //
    SMSG_FLIGHT_SPLINE_SYNC                          = 0x103A3, //
    CMSG_SET_TAXI_BENCHMARK_MODE                     = 0x103A4, //
    //SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x103A5, // :redefinition; previous def was 'enumerator'
    SMSG_REALM_SPLIT                                 = 0x01820, // 4.3.0 15050
    CMSG_REALM_SPLIT                                 = 0x01680, // 4.3.0 15050
    CMSG_MOVE_CHNG_TRANSPORT                         = 0x103A6, //
    MSG_PARTY_ASSIGNMENT                             = 0x103A7, //
    SMSG_OFFER_PETITION_ERROR                        = 0x103A8, //
    SMSG_TIME_SYNC_REQ                               = 0x103A9, //
    CMSG_TIME_SYNC_RESP                              = 0x103AA, //
    CMSG_SEND_LOCAL_EVENT                            = 0x103AB, //
    CMSG_SEND_GENERAL_TRIGGER                        = 0x103AC, //
    CMSG_SEND_COMBAT_TRIGGER                         = 0x103AD, //
    CMSG_MAELSTROM_GM_SENT_MAIL                      = 0x103AE, //
    SMSG_RESET_FAILED_NOTIFY                         = 0x103AF, //
    SMSG_REAL_GROUP_UPDATE                           = 0x103B0, //
    SMSG_LFG_DISABLED                                = 0x103B1, //
    CMSG_ACTIVE_PVP_CHEAT                            = 0x103B2, //
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY                 = 0x103B3, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE        = 0x103B4, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE  = 0x103B5, //
    SMSG_UPDATE_COMBO_POINTS                         = 0x103B6, //
    SMSG_VOICE_SESSION_ROSTER_UPDATE                 = 0x103B7, //
    SMSG_VOICE_SESSION_LEAVE                         = 0x103B8, //
    SMSG_VOICE_SESSION_ADJUST_PRIORITY               = 0x103B9, //
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST              = 0x103BA, //
    SMSG_VOICE_SET_TALKER_MUTED                      = 0x103BB, //
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE               = 0x103BC, //
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE                = 0x103BD, //
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE    = 0x103BE, //
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE              = 0x103BF, //
    MSG_MOVE_START_DESCEND                           = 0x103C0, //
    CMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x103C1, //
    SMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x103C2, //
    SMSG_SPELL_CHANCE_PROC_LOG                       = 0x103C3, //
    CMSG_MOVE_SET_RUN_SPEED                          = 0x103C4, //
    SMSG_DISMOUNT                                    = 0x103C5, //
    MSG_MOVE_UPDATE_CAN_FLY                          = 0x103C6, //
    MSG_RAID_READY_CHECK_CONFIRM                     = 0x103C7, //
    CMSG_VOICE_SESSION_ENABLE                        = 0x103C8, //
    SMSG_VOICE_SESSION_ENABLE                        = 0x103C9, //
    SMSG_VOICE_PARENTAL_CONTROLS                     = 0x103CA, //
    CMSG_GM_WHISPER                                  = 0x103CB, //
    SMSG_GM_MESSAGECHAT                              = 0x103CC, //
    MSG_GM_GEARRATING                                = 0x103CD, //
    CMSG_COMMENTATOR_ENABLE                          = 0x103CE, //
    SMSG_COMMENTATOR_STATE_CHANGED                   = 0x103CF, //
    CMSG_COMMENTATOR_GET_MAP_INFO                    = 0x103D0, //
    SMSG_COMMENTATOR_MAP_INFO                        = 0x103D1, //
    CMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x103D2, //
    SMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x103D3, //
    SMSG_COMMENTATOR_PLAYER_INFO                     = 0x103D4, //
    CMSG_COMMENTATOR_ENTER_INSTANCE                  = 0x103D5, //
    CMSG_COMMENTATOR_EXIT_INSTANCE                   = 0x103D6, //
    CMSG_COMMENTATOR_INSTANCE_COMMAND                = 0x103D7, //
    SMSG_CLEAR_TARGET                                = 0x103D8, //
    CMSG_BOT_DETECTED                                = 0x103D9, //
    SMSG_CROSSED_INEBRIATION_THRESHOLD               = 0x103DA, //
    CMSG_CHEAT_PLAYER_LOGIN                          = 0x103DB, //
    CMSG_CHEAT_PLAYER_LOOKUP                         = 0x103DC, //
    SMSG_CHEAT_PLAYER_LOOKUP                         = 0x103DD, //
    SMSG_KICK_REASON                                 = 0x054A7, // 4.3.0 15050
    MSG_RAID_READY_CHECK_FINISHED                    = 0x103DE, //
    CMSG_COMPLAIN                                    = 0x103DF, //
    SMSG_COMPLAIN_RESULT                             = 0x103E0, //
    SMSG_FEATURE_SYSTEM_STATUS                       = 0x103E1, //
    CMSG_GM_SHOW_COMPLAINTS                          = 0x103E2, //
    CMSG_GM_UNSQUELCH                                = 0x103E3, //
    CMSG_CHANNEL_SILENCE_VOICE                       = 0x103E4, //
    CMSG_CHANNEL_SILENCE_ALL                         = 0x103E5, //
    CMSG_CHANNEL_UNSILENCE_VOICE                     = 0x103E6, //
    CMSG_CHANNEL_UNSILENCE_ALL                       = 0x103E7, //
    CMSG_TARGET_CAST                                 = 0x103E8, //
    CMSG_TARGET_SCRIPT_CAST                          = 0x103E9, //
    CMSG_CHANNEL_DISPLAY_LIST                        = 0x103EA, //
    CMSG_SET_ACTIVE_VOICE_CHANNEL                    = 0x103EB, //
    CMSG_GET_CHANNEL_MEMBER_COUNT                    = 0x103EC, //
    SMSG_CHANNEL_MEMBER_COUNT                        = 0x103ED, //
    CMSG_CHANNEL_VOICE_ON                            = 0x103EE, //
    CMSG_CHANNEL_VOICE_OFF                           = 0x103EF, //
    CMSG_DEBUG_LIST_TARGETS                          = 0x103F0, //
    SMSG_DEBUG_LIST_TARGETS                          = 0x103F1, //
    SMSG_AVAILABLE_VOICE_CHANNEL                     = 0x103F2, //
    CMSG_ADD_VOICE_IGNORE                            = 0x103F3, //
    CMSG_DEL_VOICE_IGNORE                            = 0x103F4, //
    CMSG_PARTY_SILENCE                               = 0x103F5, //
    CMSG_PARTY_UNSILENCE                             = 0x103F6, //
    MSG_NOTIFY_PARTY_SQUELCH                         = 0x103F7, //
    SMSG_COMSAT_RECONNECT_TRY                        = 0x103F8, //
    SMSG_COMSAT_DISCONNECT                           = 0x103F9, //
    SMSG_COMSAT_CONNECT_FAIL                         = 0x103FA, //
    SMSG_VOICE_CHAT_STATUS                           = 0x103FB, //
    CMSG_REPORT_PVP_AFK                              = 0x103FC, //
    SMSG_REPORT_PVP_AFK_RESULT                       = 0x103FD, //
    CMSG_GUILD_BANKER_ACTIVATE                       = 0x103FE, //
    CMSG_GUILD_BANK_QUERY_TAB                        = 0x103FF, //
    SMSG_GUILD_BANK_LIST                             = 0x10400, //
    CMSG_GUILD_BANK_SWAP_ITEMS                       = 0x10401, //
    CMSG_GUILD_BANK_BUY_TAB                          = 0x10402, //
    CMSG_GUILD_BANK_UPDATE_TAB                       = 0x10403, //
    CMSG_GUILD_BANK_DEPOSIT_MONEY                    = 0x10404, //
    CMSG_GUILD_BANK_WITHDRAW_MONEY                   = 0x10405, //
    CMSG_GUILD_BANK_NOTE                             = 0x10406, //
    MSG_GUILD_BANK_LOG_QUERY                         = 0x10407, //
    CMSG_SET_CHANNEL_WATCH                           = 0x10408, //
    SMSG_USERLIST_ADD                                = 0x10409, //
    SMSG_USERLIST_REMOVE                             = 0x1040A, //
    SMSG_USERLIST_UPDATE                             = 0x1040B, //
    CMSG_CLEAR_CHANNEL_WATCH                         = 0x1040C, //
    SMSG_INSPECT_TALENT                              = 0x1040D, //
    SMSG_GOGOGO_OBSOLETE                             = 0x1040E, //
    SMSG_ECHO_PARTY_SQUELCH                          = 0x1040F, //
    CMSG_SET_TITLE_SUFFIX                            = 0x10410, //
    CMSG_SPELLCLICK                                  = 0x10411, //
    SMSG_LOOT_LIST                                   = 0x10412, //
    CMSG_GM_CHARACTER_RESTORE                        = 0x10413, //
    CMSG_GM_CHARACTER_SAVE                           = 0x10414, //
    SMSG_VOICESESSION_FULL                           = 0x10415, //
    MSG_GUILD_PERMISSIONS                            = 0x10416, //
    MSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0x10417, //
    MSG_GUILD_EVENT_LOG_QUERY                        = 0x10418, //
    CMSG_MAELSTROM_RENAME_GUILD                      = 0x10419, //
    CMSG_GET_MIRRORIMAGE_DATA                        = 0x1041A, //
    SMSG_MIRRORIMAGE_DATA                            = 0x1041B, //
    SMSG_FORCE_DISPLAY_UPDATE                        = 0x1041C, //
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK                = 0x1041D, //
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x1041E, //
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x1041F, //
    CMSG_KEEP_ALIVE                                  = 0x066A0, // 4.3.0 15050
    SMSG_RAID_READY_CHECK_ERROR                      = 0x10420, //
    CMSG_OPT_OUT_OF_LOOT                             = 0x10421, //
    MSG_QUERY_GUILD_BANK_TEXT                        = 0x10422, //
    CMSG_SET_GUILD_BANK_TEXT                         = 0x10423, //
    CMSG_SET_GRANTABLE_LEVELS                        = 0x10424, //
    CMSG_GRANT_LEVEL                                 = 0x10425, //
    CMSG_REFER_A_FRIEND                              = 0x10426, //
    MSG_GM_CHANGE_ARENA_RATING                       = 0x10427, //
    CMSG_DECLINE_CHANNEL_INVITE                      = 0x10428, //
    SMSG_GROUPACTION_THROTTLED                       = 0x10429, //
    SMSG_OVERRIDE_LIGHT                              = 0x1042A, //
    SMSG_TOTEM_CREATED                               = 0x1042B, //
    CMSG_TOTEM_DESTROYED                             = 0x1042C, //
    CMSG_EXPIRE_RAID_INSTANCE                        = 0x1042D, //
    CMSG_NO_SPELL_VARIANCE                           = 0x1042E, //
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY            = 0x1042F, //
    SMSG_QUESTGIVER_STATUS_MULTIPLE                  = 0x10430, //
    CMSG_SET_PLAYER_DECLINED_NAMES                   = 0x10431, //
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT            = 0x10432, //
    CMSG_QUERY_SERVER_BUCK_DATA                      = 0x10433, //
    CMSG_CLEAR_SERVER_BUCK_DATA                      = 0x10434, //
    SMSG_SERVER_BUCK_DATA                            = 0x10435, //
    SMSG_SEND_UNLEARN_SPELLS                         = 0x10436, //
    SMSG_PROPOSE_LEVEL_GRANT                         = 0x10437, //
    CMSG_ACCEPT_LEVEL_GRANT                          = 0x10438, //
    SMSG_REFER_A_FRIEND_FAILURE                      = 0x10439, //
    SMSG_SPLINE_MOVE_SET_FLYING                      = 0x1043A, //
    SMSG_SPLINE_MOVE_UNSET_FLYING                    = 0x1043B, //
    SMSG_SUMMON_CANCEL                               = 0x1043C, //
    CMSG_CHANGE_PERSONAL_ARENA_RATING                = 0x1043D, //
    CMSG_ALTER_APPEARANCE                            = 0x1043E, //
    SMSG_ENABLE_BARBER_SHOP                          = 0x1043F, //
    SMSG_BARBER_SHOP_RESULT                          = 0x10440, //
    CMSG_CALENDAR_GET_CALENDAR                       = 0x10441, //
    CMSG_CALENDAR_GET_EVENT                          = 0x10442, //
    CMSG_CALENDAR_GUILD_FILTER                       = 0x10443, //
    CMSG_CALENDAR_ARENA_TEAM                         = 0x10444, //
    CMSG_CALENDAR_ADD_EVENT                          = 0x10445, //
    CMSG_CALENDAR_UPDATE_EVENT                       = 0x10446, //
    CMSG_CALENDAR_REMOVE_EVENT                       = 0x10447, //
    CMSG_CALENDAR_COPY_EVENT                         = 0x10448, //
    CMSG_CALENDAR_EVENT_INVITE                       = 0x10449, //
    CMSG_CALENDAR_EVENT_RSVP                         = 0x1044A, //
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                = 0x1044B, //
    CMSG_CALENDAR_EVENT_STATUS                       = 0x1044C, //
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS             = 0x1044D, //
    SMSG_CALENDAR_SEND_CALENDAR                      = 0x1044E, //
    SMSG_CALENDAR_SEND_EVENT                         = 0x1044F, //
    SMSG_CALENDAR_FILTER_GUILD                       = 0x10450, //
    SMSG_CALENDAR_ARENA_TEAM                         = 0x10451, //
    SMSG_CALENDAR_EVENT_INVITE                       = 0x10452, //
    SMSG_CALENDAR_EVENT_INVITE_REMOVED               = 0x10453, //
    SMSG_CALENDAR_EVENT_STATUS                       = 0x10454, //
    SMSG_CALENDAR_COMMAND_RESULT                     = 0x10455, //
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                 = 0x10456, //
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED               = 0x10457, //
    SMSG_CALENDAR_EVENT_INVITE_ALERT                 = 0x10458, //
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT         = 0x10459, //
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT          = 0x1045A, //
    SMSG_CALENDAR_EVENT_REMOVED_ALERT                = 0x1045B, //
    SMSG_CALENDAR_EVENT_UPDATED_ALERT                = 0x1045C, //
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT       = 0x1045D, //
    CMSG_CALENDAR_COMPLAIN                           = 0x1045E, //
    CMSG_CALENDAR_GET_NUM_PENDING                    = 0x1045F, //
    SMSG_CALENDAR_SEND_NUM_PENDING                   = 0x10460, //
    CMSG_SAVE_DANCE                                  = 0x10461, //
    SMSG_NOTIFY_DANCE                                = 0x10462, //
    CMSG_PLAY_DANCE                                  = 0x10463, //
    SMSG_PLAY_DANCE                                  = 0x10464, //
    CMSG_LOAD_DANCES                                 = 0x10465, //
    CMSG_STOP_DANCE                                  = 0x10466, //
    SMSG_STOP_DANCE                                  = 0x10467, //
    CMSG_SYNC_DANCE                                  = 0x10468, //
    CMSG_DANCE_QUERY                                 = 0x05A02, // 4.3.0 15050
    SMSG_DANCE_QUERY_RESPONSE                        = 0x02280, // 4.3.0 15050
    SMSG_INVALIDATE_DANCE                            = 0x1046B, //
    CMSG_DELETE_DANCE                                = 0x1046C, //
    SMSG_LEARNED_DANCE_MOVES                         = 0x1046D, //
    CMSG_LEARN_DANCE_MOVE                            = 0x1046E, //
    CMSG_UNLEARN_DANCE_MOVE                          = 0x1046F, //
    CMSG_SET_RUNE_COUNT                              = 0x10470, //
    CMSG_SET_RUNE_COOLDOWN                           = 0x10471, //
    MSG_MOVE_SET_PITCH_RATE_CHEAT                    = 0x10472, //
    MSG_MOVE_SET_PITCH_RATE                          = 0x10473, //
    SMSG_FORCE_PITCH_RATE_CHANGE                     = 0x10474, //
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                 = 0x10475, //
    SMSG_SPLINE_SET_PITCH_RATE                       = 0x10476, //
    SMSG_MOVE_ABANDON_TRANSPORT                      = 0x10477, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST                 = 0x10478, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST2                = 0x10479, //
    CMSG_UPDATE_MISSILE_TRAJECTORY                   = 0x1047A, //
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                = 0x040A5, // 4.3.0 15050
    SMSG_TRIGGER_MOVIE                               = 0x1047B, //
    CMSG_COMPLETE_MOVIE                              = 0x1047C, //
    CMSG_SET_GLYPH_SLOT                              = 0x1047D, //
    CMSG_SET_GLYPH                                   = 0x1047E, //
    SMSG_ACHIEVEMENT_EARNED                          = 0x1047F, //
    SMSG_DYNAMIC_DROP_ROLL_RESULT                    = 0x10480, //
    SMSG_CRITERIA_UPDATE                             = 0x10481, //
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                  = 0x10482, //
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                = 0x10483, //
    CMSG_DISMISS_CONTROLLED_VEHICLE                  = 0x10484, //
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT                  = 0x10485, //
    SMSG_COMPRESSED_RESPOND_INSPECT_ACHIEVEMENTS     = 0x10486, //
    SMSG_COMPRESSED_ACHIEVEMENT_DATA                 = 0x10487, //
    SMSG_QUESTUPDATE_ADD_PVP_KILL                    = 0x10488, //
    CMSG_SET_CRITERIA_CHEAT                          = 0x10489, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST3                = 0x1048A, //
    CMSG_UNITANIMTIER_CHEAT                          = 0x1048B, //
    CMSG_CHAR_CUSTOMIZE                              = 0x1048C, //
    SMSG_CHAR_CUSTOMIZE                              = 0x1048D, //
    SMSG_PET_RENAMEABLE                              = 0x1048E, //
    CMSG_REQUEST_VEHICLE_EXIT                        = 0x1048F, //
    CMSG_REQUEST_PLAYER_VEHICLE_EXIT                 = 0x10490, //
    CMSG_REQUEST_VEHICLE_PREV_SEAT                   = 0x10491, //
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                   = 0x10492, //
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                 = 0x10493, //
    CMSG_PET_LEARN_TALENT                            = 0x10494, //
    CMSG_PET_UNLEARN_TALENTS                         = 0x10495, //
    SMSG_SET_PHASE_SHIFT                             = 0x10496, //
    SMSG_ALL_ACHIEVEMENT_DATA                        = 0x10497, //
    CMSG_FORCE_SAY_CHEAT                             = 0x10498, //
    SMSG_HEALTH_UPDATE                               = 0x10499, //
    SMSG_POWER_UPDATE                                = 0x1049A, //
    CMSG_GAMEOBJ_REPORT_USE                          = 0x1049B, //
    SMSG_HIGHEST_THREAT_UPDATE                       = 0x1049C, //
    SMSG_THREAT_UPDATE                               = 0x1049D, //
    SMSG_THREAT_REMOVE                               = 0x1049E, //
    SMSG_THREAT_CLEAR                                = 0x1049F, //
    SMSG_CONVERT_RUNE                                = 0x104A0, //
    SMSG_RESYNC_RUNES                                = 0x104A1, //
    SMSG_ADD_RUNE_POWER                              = 0x104A2, //
    CMSG_START_QUEST                                 = 0x104A3, //
    CMSG_REMOVE_GLYPH                                = 0x104A4, //
    CMSG_DUMP_OBJECTS                                = 0x104A5, //
    SMSG_DUMP_OBJECTS_DATA                           = 0x104A6, //
    CMSG_DISMISS_CRITTER                             = 0x104A7, //
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                  = 0x104A8, //
    CMSG_AUCTION_LIST_PENDING_SALES                  = 0x104A9, //
    SMSG_AUCTION_LIST_PENDING_SALES                  = 0x104AA, //
    SMSG_MODIFY_COOLDOWN                             = 0x104AB, //
    SMSG_PET_UPDATE_COMBO_POINTS                     = 0x104AC, //
    CMSG_ENABLETAXI                                  = 0x104AD, //
    SMSG_PRE_RESURRECT                               = 0x104AE, //
    SMSG_AURA_UPDATE_ALL                             = 0x104AF, //
    SMSG_AURA_UPDATE                                 = 0x104B0, //
    CMSG_FLOOD_GRACE_CHEAT                           = 0x104B1, //
    SMSG_SERVER_FIRST_ACHIEVEMENT                    = 0x104B2, //
    SMSG_PET_LEARNED_SPELL                           = 0x104B3, //
    SMSG_PET_REMOVED_SPELL                           = 0x104B4, //
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE          = 0x104B5, //
    CMSG_HEARTH_AND_RESURRECT                        = 0x104B6, //
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA        = 0x104B7, //
    SMSG_CRITERIA_DELETED                            = 0x104B8, //
    SMSG_ACHIEVEMENT_DELETED                         = 0x104B9, //
    CMSG_SERVER_INFO_QUERY                           = 0x104BA, //
    SMSG_SERVER_INFO_RESPONSE                        = 0x104BB, //
    CMSG_CHECK_LOGIN_CRITERIA                        = 0x104BC, //
    SMSG_SERVER_BUCK_DATA_START                      = 0x104BD, //
    CMSG_QUERY_VEHICLE_STATUS                        = 0x104BE, //
    SMSG_BATTLEGROUND_INFO_THROTTLED                 = 0x104BF, //
    SMSG_PLAYER_VEHICLE_DATA                         = 0x104C0, //
    CMSG_PLAYER_VEHICLE_ENTER                        = 0x104C1, //
    CMSG_EJECT_PASSENGER                             = 0x104C2, //
    SMSG_PET_GUIDS                                   = 0x104C3, //
    SMSG_CLIENTCACHE_VERSION                         = 0x06882, // 4.3.0 15050
    SMSG_ITEM_REFUND_INFO_RESPONSE                   = 0x104C4, //
    CMSG_ITEM_REFUND_INFO                            = 0x104C5, //
    CMSG_ITEM_REFUND                                 = 0x104C6, //
    SMSG_ITEM_REFUND_RESULT                          = 0x104C7, //
    CMSG_CORPSE_MAP_POSITION_QUERY                   = 0x104C8, //
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE          = 0x104C9, //
    CMSG_LFG_SET_ROLES_2                             = 0x104CA, //
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP               = 0x104CB, //
    SMSG_CALENDAR_ACTION_PENDING                     = 0x104CC, //
    SMSG_EQUIPMENT_SET_LIST                          = 0x104CD, //
    CMSG_EQUIPMENT_SET_SAVE                          = 0x104CE, //
    CMSG_UPDATE_PROJECTILE_POSITION                  = 0x104CF, //
    SMSG_SET_PROJECTILE_POSITION                     = 0x104D0, //
    SMSG_TALENTS_INFO                                = 0x104D1, //
    CMSG_LEARN_PREVIEW_TALENTS                       = 0x104D2, //
    CMSG_LEARN_PREVIEW_TALENTS_PET                   = 0x104D3, //
    SMSG_ARENA_OPPONENT_UPDATE                       = 0x104D4, //
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED             = 0x104D5, //
    SMSG_MULTIPLE_PACKETS                            = 0x07EA4, // 4.3.0 15050
    SMSG_MOVE_GRAVITY_DISABLE                        = 0x104D7, //
    CMSG_MOVE_GRAVITY_DISABLE_ACK                    = 0x104D8, //
    SMSG_MOVE_GRAVITY_ENABLE                         = 0x104D9, //
    CMSG_MOVE_GRAVITY_ENABLE_ACK                     = 0x104DA, //
    SMSG_MOVE_LEVITATING                             = 0x104DB, //
    SMSG_SPLINE_MOVE_UNKNOWN_1235                    = 0x104DC, //
    SMSG_SPLINE_MOVE_UNKNOWN_1236                    = 0x104DD, //
    CMSG_EQUIPMENT_SET_USE                           = 0x104DE, //
    SMSG_EQUIPMENT_SET_USE_RESULT                    = 0x104DF, //
    SMSG_UNKNOWN_1240                                = 0x104E0, //
    CMSG_CHAR_FACTION_CHANGE                         = 0x104E1, //
    SMSG_CHAR_FACTION_CHANGE                         = 0x002A5, // 4.3.0 15050
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                = 0x104E2, //
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE       = 0x104E3, //
    SMSG_BATTLEFIELD_MGR_ENTERED                     = 0x104E4, //
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                = 0x104E5, //
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE       = 0x104E6, //
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST               = 0x104E7, //
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE      = 0x104E8, //
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING               = 0x104E9, //
    SMSG_BATTLEFIELD_MGR_EJECTED                     = 0x104EA, //
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                = 0x104EB, //
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                = 0x104EC, //
    CMSG_WARGAME_ACCEPT                              = 0x104ED, //
    CMSG_WARGAME_REQUEST                             = 0x104EE, //
    SMSG_WARGAME_REQUEST_RESPONSE                    = 0x104EF, //
    SMSG_WARGAME_REQUEST_SENT                        = 0x104F0, //
    MSG_SET_RAID_DIFFICULTY                          = 0x104F1, //
    SMSG_TOGGLE_XP_GAIN                              = 0x104F2, //
    SMSG_GMRESPONSE_DB_ERROR                         = 0x104F3, //
    SMSG_GMRESPONSE_RECEIVED                         = 0x104F4, //
    CMSG_GMRESPONSE_RESOLVE                          = 0x104F5, //
    SMSG_GMRESPONSE_STATUS_UPDATE                    = 0x104F6, //
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x104F7, //
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x104F8, //
    CMSG_CHAR_RACE_CHANGE                            = 0x104F9, //
    SMSG_TALENTS_INVOLUNTARILY_RESET                 = 0x104FA, //
    SMSG_LOOT_SLOT_CHANGED                           = 0x104FB, //
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                = 0x01E80, // 4.3.0 15050
    CMSG_QUERY_QUESTS_COMPLETED                      = 0x104FC, //
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE             = 0x104FD, //
    CMSG_GM_REPORT_LAG                               = 0x104FE, //
    SMSG_CORPSE_NOT_IN_INSTANCE                      = 0x104FF, //
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                   = 0x10500, //
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                   = 0x10501, //
    SMSG_CAMERA_SHAKE                                = 0x10502, //
    SMSG_UPDATE_ITEM_ENCHANTMENTS                    = 0x10503, //
    SMSG_REDIRECT_CLIENT                             = 0x00703, // 4.3.0 15050
    CMSG_REDIRECTION_FAILED                          = 0x10504, //
    SMSG_UNKNOWN_1295                                = 0x10505, //
    CMSG_UNKNOWN_1296                                = 0x05108, // 4.3.0 15050, //Unknown opcode Name
    SMSG_FORCE_SEND_QUEUED_PACKETS                   = 0x01322, // 4.3.0 15050
    CMSG_REDIRECTION_AUTH_PROOF                      = 0x04108, // 4.3.0 15050
    SMSG_COMBAT_LOG_MULTIPLE                         = 0x10506, //
    SMSG_LFG_OPEN_FROM_GOSSIP                        = 0x10507, //
    SMSG_UNKNOWN_1302                                = 0x10508, //
    CMSG_UNKNOWN_1303                                = 0x10509, //
    SMSG_UNKNOWN_1304                                = 0x1050A, //
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND          = 0x1050B, //
    SMSG_UNKNOWN_1308                                = 0x1050C, //
    CMSG_TRANSFORM                                   = 0x04577, //
    SMSG_UNKNOWN_1310                                = 0x1050D, //
    SMSG_UNKNOWN_1311                                = 0x1050E, //
    SMSG_UNKNOWN_1312                                = 0x1050F, //
    SMSG_UNKNOWN_1314                                = 0x10510, //
    SMSG_UNKNOWN_1315                                = 0x10511, //
    SMSG_UNKNOWN_1316                                = 0x10512, //
    SMSG_UNKNOWN_1317                                = 0x10513, //
    CMSG_UNKNOWN_1320                                = 0x10514, //
    SMSG_UNKNOWN_1329                                = 0x02D57, //
    SMSG_BATTLEGROUND_IN_PROGRESS                    = 0x10515, //
    SMSG_BATTLEGROUND_EXIT_QUEUE                     = 0x10516, //
    SMSG_BATTLEGROUND_WAIT_JOIN                      = 0x10517, //
    CMSG_BATTLEGROUND_PORT_AND_LEAVE                 = 0x10518, //
    SMSG_GUILD_XP_LIMIT                              = 0x10519, //
    CMSG_GUILD_QUERY_XP                              = 0x1051A, //
    SMSG_GUILD_XP                                    = 0x1051B, //
    SMSG_GUILD_UPDATE_PARTY_STATE                    = 0x1051C, //
    CMSG_GUILD_UPDATE_PARTY_STATE                    = 0x1051D, //
    SMSG_SEND_QUEUED_PACKETS                         = 0x1051E, //
    CMSG_REDIRECT_AUTH_PROOF                         = 0x1051F, //
    CMSG_AUTO_DECLINE_GUILD_INVITES                  = 0x10520, //
    CMSG_SET_PRIMARY_TALENT_TREE                     = 0x10521, //
    CMSG_GROUP_SET_ROLES                             = 0x10522, //
    CMSG_WORLD_LOGIN                                 = 0x00976, // 4.3.0 15050
    SMSG_UNKNOWN_65508                               = 0x10523, //
    //SMSG_INIT_CURRENCY                               = 0x10524, // :redefinition; previous def was 'enumerator'
    //SMSG_UPDATE_CURRENCY                             = 0x10525, // :redefinition; previous def was 'enumerator'
    //SMSG_UPDATE_CURRENCY_WEEK_LIMIT                  = 0x10526, // :redefinition; previous def was 'enumerator'
    SMSG_GUILD_ACHIEVEMENT_EARNED                    = 0x10527, //
    SMSG_GUILD_ACHIEVEMENT_DATA                      = 0x10528, //
    CMSG_UI_TIME_REQUEST                             = 0x10529, //
    SMSG_UI_TIME                                     = 0x1052A, //
    CMSG_RETURN_TO_GRAVEYARD                         = 0x1052B, //
    SMSG_UNKNOWN_1330                                = 0x1052C, //
    CMSG_REFORGE_ITEM                                = 0x1052D, //
    CMSG_COMPLETED_ARTIFACTS                         = 0x1052E, //
    SMSG_COMPLETED_ARTIFACTS                         = 0x1052F, // structure: uint32 (count) loop: uint32(id), uint32(date), uint32(number of times completed) :endloop
    SMSG_ARTIFACT_COMPLETED                          = 0x10530, //
    CMSG_SET_FOCUSED_ACHIEVEMENT                     = 0x10534, //
    SMSG_REFORGE_OPEN_FROM_GOSSIP                    = 0x10535, //
    SMSG_UNKNOWN_GOLD                                = 0x10536, // gives gold to the player
    SMSG_REQUEST_WAR_GAME_RESPONSE                   = 0x10537, //
    SMSG_SERVER_MESSAGE_BOX                          = 0x10538, // Server msgbox-like 
    SMSG_TALENT_ERROR                                = 0x10539, //
    SMSG_SEND_ERROR_MESSAGE                          = 0x1053A, // this has its own enum u8+u32+u32 special
    CMSG_GET_GUILD_ACHIEVEMENT_MEMBERS               = 0x1053B, //
    SMSG_SEND_GUILD_ACHIEVEMENT_MEMBERS              = 0x1053C, //
    CMSG_CLEAR_RAID_MARKER                           = 0x1053D, //
    CMSG_REQUEST_GUILD_PARTY_STATE                   = 0x1053E, //
    CMSG_GET_GUILD_MEMBER_RECIPES                    = 0x1053F, //
    CMSG_QUERY_GUILD_MEMBERS_FOR_RECIPE              = 0x10540, //
    CMSG_GUILD_NEWS_SET_STICKY                       = 0x10541, //
    CMSG_LOG_DISCONNECT                              = 0x00108, // 4.3.0 15050
    MSG_CHECK_CONNECTION                             = 0x04F57, // 4.3.0 15050
    NUM_MSG_TYPES                                    = 0x10542  // last unknown opcode + 1.
};

extern void InitOpcodeTable();

///- Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED                                        // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    // process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   // packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      // packet is thread-safe - process it in Map::Update()
};

class WorldPacket;

struct OpcodeHandler
{
    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    void (WorldSession::*handler)(WorldPacket& recvPacket);
};

extern OpcodeHandler opcodeTable[NUM_MSG_TYPES];

/// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(uint32 id)
{
    if (id >= NUM_MSG_TYPES)
        return "Received unknown opcode, it's more than max!";
    return opcodeTable[id].name;
}
#endif
/// @}
