/*
 * Copyright (C) 2011-2013 Project SkyFire <http://www.projectskyfire.org/>
 * Copyright (C) 2008-2013 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2013 MaNGOS <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __SKYFIRE_LANGUAGE_H
#define __SKYFIRE_LANGUAGE_H

enum SkyFireStrings
{
    // for chat commands
    LANGUAGE_SELECT_CHARACTER_OR_CREATURE   = 1,
    LANGUAGE_SELECT_CREATURE                = 2,

    // level 0 chat
    LANGUAGE_SYSTEMMESSAGE                  = 3,
    LANGUAGE_EVENTMESSAGE                   = 4,
    LANGUAGE_NO_HELP_CMD                    = 5,
    LANGUAGE_NO_CMD                         = 6,
    LANGUAGE_NO_SUBCMD                      = 7,
    LANGUAGE_SUBCMDS_LIST                   = 8,
    LANGUAGE_AVIABLE_CMD                    = 9,
    LANGUAGE_CMD_SYNTAX                     = 10,
    LANGUAGE_ACCOUNT_LEVEL                  = 11,
    LANGUAGE_CONNECTED_USERS                = 12,
    LANGUAGE_UPTIME                         = 13,
    LANGUAGE_PLAYER_SAVED                   = 14,
    LANGUAGE_PLAYERS_SAVED                  = 15,
    LANGUAGE_GMS_ON_SRV                     = 16,
    LANGUAGE_GMS_NOT_LOGGED                 = 17,
    LANGUAGE_YOU_IN_FLIGHT                  = 18,
    LANGUAGE_UPDATE_DIFF                    = 19,
    LANGUAGE_SHUTDOWN_TIMELEFT              = 20,
    LANGUAGE_CHARACTER_IN_FLIGHT            = 21,
    LANGUAGE_CHARACTER_NON_MOUNTED          = 22,
    LANGUAGE_YOU_IN_COMBAT                  = 23,
    LANGUAGE_YOU_USED_IT_RECENTLY           = 24,
    LANGUAGE_COMMAND_NOTCHANGEPASSWORD      = 25,
    LANGUAGE_COMMAND_PASSWORD               = 26,
    LANGUAGE_COMMAND_WRONGOLDPASSWORD       = 27,
    LANGUAGE_COMMAND_ACCLOCKLOCKED          = 28,
    LANGUAGE_COMMAND_ACCLOCKUNLOCKED        = 29,
    LANGUAGE_SPELL_RANK                     = 30,
    LANGUAGE_KNOWN                          = 31,
    LANGUAGE_LEARN                          = 32,
    LANGUAGE_PASSIVE                        = 33,
    LANGUAGE_TALENT                         = 34,
    LANGUAGE_ACTIVE                         = 35,
    LANGUAGE_COMPLETE                       = 36,
    LANGUAGE_OFFLINE                        = 37,
    LANGUAGE_ON                             = 38,
    LANGUAGE_OFF                            = 39,
    LANGUAGE_YOU_ARE                        = 40,
    LANGUAGE_VISIBLE                        = 41,
    LANGUAGE_INVISIBLE                      = 42,
    LANGUAGE_DONE                           = 43,
    LANGUAGE_YOU                            = 44,
    LANGUAGE_UNKNOWN                        = 45,
    LANGUAGE_ERROR                          = 46,
    LANGUAGE_NON_EXIST_CHARACTER            = 47,
    LANGUAGE_FRIEND_IGNORE_UNKNOWN          = 48,
    LANGUAGE_LEVEL_MINREQUIRED              = 49,
    LANGUAGE_LEVEL_MINREQUIRED_AND_ITEM     = 50,
    LANGUAGE_NPC_TAINER_HELLO               = 51,
    LANGUAGE_COMMAND_INVALID_ITEM_COUNT     = 52,
    LANGUAGE_COMMAND_MAIL_ITEMS_LIMIT       = 53,
    LANGUAGE_NEW_PASSWORDS_NOT_MATCH        = 54,
    LANGUAGE_PASSWORD_TOO_LONG              = 55,
    LANGUAGE_MOTD_CURRENT                   = 56,
    LANGUAGE_USING_WORLD_DB                 = 57,
    LANGUAGE_USING_SCRIPT_LIB               = 58,
    LANGUAGE_USING_EVENT_AI                 = 59,
    LANGUAGE_CONNECTED_PLAYERS              = 60,
    LANGUAGE_ACCOUNT_ADDON                  = 61,
    LANGUAGE_IMPROPER_VALUE                 = 62,
    // Room for more level 0              63-99 not used

    // level 1 chat
    LANGUAGE_GLOBAL_NOTIFY                  = 100,
    LANGUAGE_MAP_POSITION                   = 101,
    LANGUAGE_IS_TELEPORTED                  = 102,
    LANGUAGE_CANNOT_SUMMON_TO_INST          = 103,
    LANGUAGE_CANNOT_GO_TO_INST_PARTY        = 104,
    LANGUAGE_CANNOT_GO_TO_INST_GM           = 105,
    LANGUAGE_CANNOT_GO_INST_INST            = 106,
    LANGUAGE_CANNOT_SUMMON_INST_INST        = 107,
    LANGUAGE_SUMMONING                      = 108,
    LANGUAGE_SUMMONED_BY                    = 109,
    LANGUAGE_TELEPORTING_TO                 = 110,
    LANGUAGE_TELEPORTED_TO_BY               = 111,
    LANGUAGE_NO_PLAYER                      = 112,
    LANGUAGE_APPEARING_AT                   = 113,
    LANGUAGE_APPEARING_TO                   = 114,
    LANGUAGE_BAD_VALUE                      = 115,
    LANGUAGE_NO_CHARACTER_SELECTED          = 116,
    LANGUAGE_NOT_IN_GROUP                   = 117,

    LANGUAGE_YOU_CHANGE_HP                  = 118,
    LANGUAGE_YOURS_HP_CHANGED               = 119,
    LANGUAGE_YOU_CHANGE_MANA                = 120,
    LANGUAGE_YOURS_MANA_CHANGED             = 121,
    LANGUAGE_YOU_CHANGE_ENERGY              = 122,
    LANGUAGE_YOURS_ENERGY_CHANGED           = 123,

    LANGUAGE_CURRENT_ENERGY                 = 124,              //log
    LANGUAGE_YOU_CHANGE_RAGE                = 125,
    LANGUAGE_YOURS_RAGE_CHANGED             = 126,
    LANGUAGE_YOU_CHANGE_LVL                 = 127,
    LANGUAGE_CURRENT_FACTION                = 128,
    LANGUAGE_WRONG_FACTION                  = 129,
    LANGUAGE_YOU_CHANGE_FACTION             = 130,
    LANGUAGE_YOU_CHANGE_SPELLFLATID         = 131,
    LANGUAGE_YOURS_SPELLFLATID_CHANGED      = 132,
    LANGUAGE_YOU_GIVE_TAXIS                 = 133,
    LANGUAGE_YOU_REMOVE_TAXIS               = 134,
    LANGUAGE_YOURS_TAXIS_ADDED              = 135,
    LANGUAGE_YOURS_TAXIS_REMOVED            = 136,

    LANGUAGE_YOU_CHANGE_ASPEED              = 137,
    LANGUAGE_YOURS_ASPEED_CHANGED           = 138,
    LANGUAGE_YOU_CHANGE_SPEED               = 139,
    LANGUAGE_YOURS_SPEED_CHANGED            = 140,
    LANGUAGE_YOU_CHANGE_SWIM_SPEED          = 141,
    LANGUAGE_YOURS_SWIM_SPEED_CHANGED       = 142,
    LANGUAGE_YOU_CHANGE_BACK_SPEED          = 143,
    LANGUAGE_YOURS_BACK_SPEED_CHANGED       = 144,
    LANGUAGE_YOU_CHANGE_FLY_SPEED           = 145,
    LANGUAGE_YOURS_FLY_SPEED_CHANGED        = 146,

    LANGUAGE_YOU_CHANGE_SIZE                = 147,
    LANGUAGE_YOURS_SIZE_CHANGED             = 148,
    LANGUAGE_NO_MOUNT                       = 149,
    LANGUAGE_YOU_GIVE_MOUNT                 = 150,
    LANGUAGE_MOUNT_GIVED                    = 151,

    LANGUAGE_CURRENT_MONEY                  = 152,
    LANGUAGE_YOU_TAKE_ALL_MONEY             = 153,
    LANGUAGE_YOURS_ALL_MONEY_GONE           = 154,
    LANGUAGE_YOU_TAKE_MONEY                 = 155,
    LANGUAGE_YOURS_MONEY_TAKEN              = 156,
    LANGUAGE_YOU_GIVE_MONEY                 = 157,
    LANGUAGE_YOURS_MONEY_GIVEN              = 158,
    LANGUAGE_YOU_HEAR_SOUND                 = 159,

    LANGUAGE_NEW_MONEY                      = 160,              // Log

    LANGUAGE_REMOVE_BIT                     = 161,
    LANGUAGE_SET_BIT                        = 162,
    LANGUAGE_COMMAND_TELE_TABLEEMPTY        = 163,
    LANGUAGE_COMMAND_TELE_NOTFOUND          = 164,
    LANGUAGE_COMMAND_TELE_PARAMETER         = 165,
    LANGUAGE_COMMAND_TELE_NOLOCATION        = 166,
    //                                    167               // not used
    LANGUAGE_COMMAND_TELE_LOCATION          = 168,

    LANGUAGE_MAIL_SENT                      = 169,
    LANGUAGE_SOUND_NOT_EXIST                = 170,
    LANGUAGE_CANT_TELEPORT_SELF             = 171,
    LANGUAGE_CONSOLE_COMMAND                = 172,
    LANGUAGE_YOU_CHANGE_RUNIC_POWER         = 173,
    LANGUAGE_YOURS_RUNIC_POWER_CHANGED      = 174,
    LANGUAGE_LIQUID_STATUS                  = 175,
    LANGUAGE_IS_NOTE                        = 176,
    // Room for more level 1              176-199 not used

    // level 2 chat
    LANGUAGE_NO_SELECTION                   = 200,
    LANGUAGE_OBJECT_GUID                    = 201,
    LANGUAGE_TOO_LONG_NAME                  = 202,
    LANGUAGE_CHARS_ONLY                     = 203,
    LANGUAGE_TOO_LONG_SUBNAME               = 204,
    LANGUAGE_NOT_IMPLEMENTED                = 205,

    LANGUAGE_ITEM_ADDED_TO_LIST             = 206,
    LANGUAGE_ITEM_NOT_FOUND                 = 207,
    LANGUAGE_ITEM_DELETED_FROM_LIST         = 208,
    LANGUAGE_ITEM_NOT_IN_LIST               = 209,
    LANGUAGE_ITEM_ALREADY_IN_LIST           = 210,

    LANGUAGE_RESET_SPELLS_ONLINE            = 211,
    LANGUAGE_RESET_SPELLS_OFFLINE           = 212,
    LANGUAGE_RESET_TALENTS_ONLINE           = 213,
    LANGUAGE_RESET_TALENTS_OFFLINE          = 214,
    LANGUAGE_RESET_SPELLS                   = 215,
    LANGUAGE_RESET_TALENTS                  = 216,

    LANGUAGE_RESETALL_UNKNOWN_CASE          = 217,
    LANGUAGE_RESETALL_SPELLS                = 218,
    LANGUAGE_RESETALL_TALENTS               = 219,

    LANGUAGE_WAYPOINT_NOTFOUND              = 220,
    LANGUAGE_WAYPOINT_NOTFOUNDLAST          = 221,
    LANGUAGE_WAYPOINT_NOTFOUNDSEARCH        = 222,
    LANGUAGE_WAYPOINT_NOTFOUNDDBPROBLEM     = 223,
    LANGUAGE_WAYPOINT_CREATSELECTED         = 224,
    LANGUAGE_WAYPOINT_CREATNOTFOUND         = 225,
    LANGUAGE_WAYPOINT_VP_SELECT             = 226,
    LANGUAGE_WAYPOINT_VP_NOTFOUND           = 227,
    LANGUAGE_WAYPOINT_VP_NOTCREATED         = 228,
    LANGUAGE_WAYPOINT_VP_ALLREMOVED         = 229,
    LANGUAGE_WAYPOINT_NOTCREATED            = 230,
    LANGUAGE_WAYPOINT_NOGUID                = 231,
    LANGUAGE_WAYPOINT_NOWAYPOINTGIVEN       = 232,
    LANGUAGE_WAYPOINT_ARGUMENTREQ           = 233,
    LANGUAGE_WAYPOINT_ADDED                 = 234,
    LANGUAGE_WAYPOINT_ADDED_NO              = 235,
    LANGUAGE_WAYPOINT_CHANGED               = 236,
    LANGUAGE_WAYPOINT_CHANGED_NO            = 237,
    LANGUAGE_WAYPOINT_EXPORTED              = 238,
    LANGUAGE_WAYPOINT_NOTHINGTOEXPORT       = 239,
    LANGUAGE_WAYPOINT_IMPORTED              = 240,
    LANGUAGE_WAYPOINT_REMOVED               = 241,
    LANGUAGE_WAYPOINT_NOTREMOVED            = 242,
    LANGUAGE_WAYPOINT_TOOFAR1               = 243,
    LANGUAGE_WAYPOINT_TOOFAR2               = 244,
    LANGUAGE_WAYPOINT_TOOFAR3               = 245,
    LANGUAGE_WAYPOINT_INFO_TITLE            = 246,
    LANGUAGE_WAYPOINT_INFO_WAITTIME         = 247,
    LANGUAGE_WAYPOINT_INFO_MODEL            = 248,
    LANGUAGE_WAYPOINT_INFO_EMOTE            = 249,
    LANGUAGE_WAYPOINT_INFO_SPELL            = 250,
    LANGUAGE_WAYPOINT_INFO_TEXT             = 251,
    LANGUAGE_WAYPOINT_INFO_AISCRIPT         = 252,

    LANGUAGE_RENAME_PLAYER                  = 253,
    LANGUAGE_RENAME_PLAYER_GUID             = 254,

    LANGUAGE_WAYPOINT_WPCREATNOTFOUND       = 255,
    LANGUAGE_WAYPOINT_NPCNOTFOUND           = 256,

    LANGUAGE_MOVE_TYPE_SET                  = 257,
    LANGUAGE_MOVE_TYPE_SET_NODEL            = 258,
    LANGUAGE_USE_BOL                        = 259,
    LANGUAGE_VALUE_SAVED                    = 260,
    LANGUAGE_VALUE_SAVED_REJOIN             = 261,

    LANGUAGE_COMMAND_GOAREATRNOTFOUND       = 262,
    LANGUAGE_INVALID_TARGET_COORD           = 263,
    LANGUAGE_INVALID_ZONE_COORD             = 264,
    LANGUAGE_INVALID_ZONE_MAP               = 265,
    LANGUAGE_COMMAND_TARGETOBJNOTFOUND      = 266,
    LANGUAGE_COMMAND_GOOBJNOTFOUND          = 267,
    LANGUAGE_COMMAND_GOCREATNOTFOUND        = 268,
    LANGUAGE_COMMAND_GOCREATMULTIPLE        = 269,
    LANGUAGE_COMMAND_DELCREATMESSAGE        = 270,
    LANGUAGE_COMMAND_CREATUREMOVED          = 271,
    LANGUAGE_COMMAND_CREATUREATSAMEMAP      = 272,
    LANGUAGE_COMMAND_OBJNOTFOUND            = 273,
    LANGUAGE_COMMAND_DELOBJREFERCREATURE    = 274,
    LANGUAGE_COMMAND_DELOBJMESSAGE          = 275,
    LANGUAGE_COMMAND_TURNOBJMESSAGE         = 276,
    LANGUAGE_COMMAND_MOVEOBJMESSAGE         = 277,
    LANGUAGE_COMMAND_VENDORSELECTION        = 278,
    LANGUAGE_COMMAND_NEEDITEMSEND           = 279,
    LANGUAGE_COMMAND_ADDVENDORITEMITEMS     = 280,
    LANGUAGE_COMMAND_KICKSELF               = 281,
    LANGUAGE_COMMAND_KICKMESSAGE            = 282,
    LANGUAGE_COMMAND_DISABLE_CHAT_DELAYED   = 283,
    LANGUAGE_COMMAND_WHISPERACCEPTING       = 284,
    LANGUAGE_COMMAND_WHISPERON              = 285,
    LANGUAGE_COMMAND_WHISPEROFF             = 286,
    LANGUAGE_COMMAND_CREATGUIDNOTFOUND      = 287,
      // TICKET STRINGS NEED REWRITE // 288-296 FREE

      // END
    LANGUAGE_COMMAND_SPAWNDIST              = 297,
    LANGUAGE_COMMAND_SPAWNTIME              = 298,
    LANGUAGE_COMMAND_MODIFY_HONOR           = 299,

    LANGUAGE_YOUR_CHAT_DISABLED             = 300,
    LANGUAGE_YOU_DISABLE_CHAT               = 301,
    LANGUAGE_CHAT_ALREADY_ENABLED           = 302,
    LANGUAGE_YOUR_CHAT_ENABLED              = 303,
    LANGUAGE_YOU_ENABLE_CHAT                = 304,

    LANGUAGE_COMMAND_MODIFY_REP             = 305,
    LANGUAGE_COMMAND_MODIFY_ARENA           = 306,
    LANGUAGE_COMMAND_FACTION_NOTFOUND       = 307,
    LANGUAGE_COMMAND_FACTION_UNKNOWN        = 308,
    LANGUAGE_COMMAND_FACTION_INVPARAM       = 309,
    LANGUAGE_COMMAND_FACTION_DELTA          = 310,
    LANGUAGE_FACTION_LIST                   = 311,
    LANGUAGE_FACTION_VISIBLE                = 312,
    LANGUAGE_FACTION_ATWAR                  = 313,
    LANGUAGE_FACTION_PEACE_FORCED           = 314,
    LANGUAGE_FACTION_HIDDEN                 = 315,
    LANGUAGE_FACTION_INVISIBLE_FORCED       = 316,
    LANGUAGE_FACTION_INACTIVE               = 317,
    LANGUAGE_REP_HATED                      = 318,
    LANGUAGE_REP_HOSTILE                    = 319,
    LANGUAGE_REP_UNFRIENDLY                 = 320,
    LANGUAGE_REP_NEUTRAL                    = 321,
    LANGUAGE_REP_FRIENDLY                   = 322,
    LANGUAGE_REP_HONORED                    = 323,
    LANGUAGE_REP_REVERED                    = 324,
    LANGUAGE_REP_EXALTED                    = 325,
    LANGUAGE_COMMAND_FACTION_NOREP_ERROR    = 326,
    LANGUAGE_FACTION_NOREPUTATION           = 327,
    LANGUAGE_LOOKUP_PLAYER_ACCOUNT          = 328,
    LANGUAGE_LOOKUP_PLAYER_CHARACTER        = 329,
    LANGUAGE_NO_PLAYERS_FOUND               = 330,
    LANGUAGE_EXTENDED_COST_NOT_EXIST        = 331,
    LANGUAGE_GM_ON                          = 332,
    LANGUAGE_GM_OFF                         = 333,
    LANGUAGE_GM_CHAT_ON                     = 334,
    LANGUAGE_GM_CHAT_OFF                    = 335,
    LANGUAGE_YOU_REPAIR_ITEMS               = 336,
    LANGUAGE_YOUR_ITEMS_REPAIRED            = 337,
    LANGUAGE_YOU_SET_WATERWALK              = 338,
    LANGUAGE_YOUR_WATERWALK_SET             = 339,
    LANGUAGE_CREATURE_FOLLOW_YOU_NOW        = 340,
    LANGUAGE_CREATURE_NOT_FOLLOW_YOU        = 341,
    LANGUAGE_CREATURE_NOT_FOLLOW_YOU_NOW    = 342,
    LANGUAGE_CREATURE_NON_TAMEABLE          = 343,
    LANGUAGE_YOU_ALREADY_HAVE_PET           = 344,
    LANGUAGE_CUSTOMIZE_PLAYER               = 345,
    LANGUAGE_CUSTOMIZE_PLAYER_GUID          = 346,
    LANGUAGE_COMMAND_GOTAXINODENOTFOUND     = 347,
    LANGUAGE_GAMEOBJECT_HAVE_INVALID_DATA   = 348,
    LANGUAGE_TITLE_LIST_CHAT                = 349,
    LANGUAGE_TITLE_LIST_CONSOLE             = 350,
    LANGUAGE_COMMAND_NOTITLEFOUND           = 351,
    LANGUAGE_INVALID_TITLE_ID               = 352,
    LANGUAGE_TITLE_ADD_RES                  = 353,
    LANGUAGE_TITLE_REMOVE_RES               = 354,
    LANGUAGE_TITLE_CURRENT_RES              = 355,
    LANGUAGE_CURRENT_TITLE_RESET            = 356,
    // Room for more level 2              357-399 not used

    // level 3 chat
    LANGUAGE_SCRIPTS_RELOADED               = 400,
    LANGUAGE_YOU_CHANGE_SECURITY            = 401,
    LANGUAGE_YOURS_SECURITY_CHANGED         = 402,
    LANGUAGE_YOURS_SECURITY_IS_LOW          = 403,
    LANGUAGE_CREATURE_MOVE_DISABLED         = 404,
    LANGUAGE_CREATURE_MOVE_ENABLED          = 405,
    LANGUAGE_NO_WEATHER                     = 406,
    LANGUAGE_WEATHER_DISABLED               = 407,

    LANGUAGE_BAN_YOUBANNED                  = 408,
    LANGUAGE_BAN_YOUPERMBANNED              = 409,
    LANGUAGE_BAN_NOTFOUND                   = 410,

    LANGUAGE_UNBAN_UNBANNED                 = 411,
    LANGUAGE_UNBAN_ERROR                    = 412,

    LANGUAGE_ACCOUNT_NOT_EXIST              = 413,

    LANGUAGE_BANINFO_NOCHARACTER            = 414,
    LANGUAGE_BANINFO_NOIP                   = 415,
    LANGUAGE_BANINFO_NOACCOUNTBAN           = 416,
    LANGUAGE_BANINFO_BANHISTORY             = 417,
    LANGUAGE_BANINFO_HISTORYENTRY           = 418,
    LANGUAGE_BANINFO_INFINITE               = 419,
    LANGUAGE_BANINFO_NEVER                  = 420,
    LANGUAGE_BANINFO_YES                    = 421,
    LANGUAGE_BANINFO_NO                     = 422,
    LANGUAGE_BANINFO_IPENTRY                = 423,

    LANGUAGE_BANLIST_NOIP                   = 424,
    LANGUAGE_BANLIST_NOACCOUNT              = 425,
    LANGUAGE_BANLIST_NOCHARACTER            = 426,
    LANGUAGE_BANLIST_MATCHINGIP             = 427,
    LANGUAGE_BANLIST_MATCHINGACCOUNT        = 428,

    LANGUAGE_COMMAND_LEARN_MANY_SPELLS      = 429,
    LANGUAGE_COMMAND_LEARN_CLASS_SPELLS     = 430,
    LANGUAGE_COMMAND_LEARN_CLASS_TALENTS    = 431,
    LANGUAGE_COMMAND_LEARN_ALL_LANG         = 432,
    LANGUAGE_COMMAND_LEARN_ALL_CRAFT        = 433,
    LANGUAGE_COMMAND_COULDNOTFIND           = 434,
    LANGUAGE_COMMAND_ITEMIDINVALID          = 435,
    LANGUAGE_COMMAND_NOITEMFOUND            = 436,
    LANGUAGE_COMMAND_LISTOBJINVALIDID       = 437,
    LANGUAGE_COMMAND_LISTITEMMESSAGE        = 438,
    LANGUAGE_COMMAND_LISTOBJMESSAGE         = 439,
    LANGUAGE_COMMAND_INVALIDCREATUREID      = 440,
    LANGUAGE_COMMAND_LISTCREATUREMESSAGE    = 441,
    LANGUAGE_COMMAND_NOAREAFOUND            = 442,
    LANGUAGE_COMMAND_NOITEMSETFOUND         = 443,
    LANGUAGE_COMMAND_NOSKILLFOUND           = 444,
    LANGUAGE_COMMAND_NOSPELLFOUND           = 445,
    LANGUAGE_COMMAND_NOQUESTFOUND           = 446,
    LANGUAGE_COMMAND_NOCREATUREFOUND        = 447,
    LANGUAGE_COMMAND_NOGAMEOBJECTFOUND      = 448,
    LANGUAGE_COMMAND_GRAVEYARDNOEXIST       = 449,
    LANGUAGE_COMMAND_GRAVEYARDALRLINKED     = 450,
    LANGUAGE_COMMAND_GRAVEYARDLINKED        = 451,
    LANGUAGE_COMMAND_GRAVEYARDWRONGZONE     = 452,
    //                                  = 453, see LANGUAGE_PINFO_BAN
    LANGUAGE_COMMAND_GRAVEYARDERROR         = 454,
    LANGUAGE_COMMAND_GRAVEYARD_NOTEAM       = 455,
    LANGUAGE_COMMAND_GRAVEYARD_ANY          = 456,
    LANGUAGE_COMMAND_GRAVEYARD_ALLIANCE     = 457,
    LANGUAGE_COMMAND_GRAVEYARD_HORDE        = 458,
    LANGUAGE_COMMAND_GRAVEYARDNEAREST       = 459,
    LANGUAGE_COMMAND_ZONENOGRAVEYARDS       = 460,
    LANGUAGE_COMMAND_ZONENOGRAFACTION       = 461,
    LANGUAGE_COMMAND_TP_ALREADYEXIST        = 462,
    LANGUAGE_COMMAND_TP_ADDED               = 463,
    LANGUAGE_COMMAND_TP_ADDEDERR            = 464,
    LANGUAGE_COMMAND_TP_DELETED             = 465,
    LANGUAGE_COMMAND_NOTAXINODEFOUND        = 466,
    LANGUAGE_COMMAND_TARGET_LISTAURAS       = 467,
    LANGUAGE_COMMAND_TARGET_AURADETAIL      = 468,
    LANGUAGE_COMMAND_TARGET_LISTAURATYPE    = 469,
    LANGUAGE_COMMAND_TARGET_AURASIMPLE      = 470,

    LANGUAGE_COMMAND_QUEST_NOTFOUND         = 471,
    LANGUAGE_COMMAND_QUEST_STARTFROMITEM    = 472,
    LANGUAGE_COMMAND_QUEST_REMOVED          = 473,
    LANGUAGE_COMMAND_QUEST_REWARDED         = 474,
    LANGUAGE_COMMAND_QUEST_COMPLETE         = 475,
    LANGUAGE_COMMAND_QUEST_ACTIVE           = 476,

    LANGUAGE_COMMAND_FLYMODE_STATUS         = 477,

    LANGUAGE_COMMAND_OPCODESENT             = 478,

    LANGUAGE_COMMAND_IMPORT_SUCCESS         = 479,
    LANGUAGE_COMMAND_IMPORT_FAILED          = 480,
    LANGUAGE_COMMAND_EXPORT_SUCCESS         = 481,
    LANGUAGE_COMMAND_EXPORT_FAILED          = 482,

    LANGUAGE_COMMAND_SPELL_BROKEN           = 483,

    LANGUAGE_SET_SKILL                      = 484,
    LANGUAGE_SET_SKILL_ERROR                = 485,

    LANGUAGE_INVALID_SKILL_ID               = 486,
    LANGUAGE_LEARNING_GM_SKILLS             = 487,
    LANGUAGE_YOU_KNOWN_SPELL                = 488,
    LANGUAGE_TARGET_KNOWN_SPELL             = 489,
    LANGUAGE_UNKNOWN_SPELL                  = 490,
    LANGUAGE_FORGET_SPELL                   = 491,
    LANGUAGE_REMOVEALL_COOLDOWN             = 492,
    LANGUAGE_REMOVE_COOLDOWN                = 493,

    LANGUAGE_ADDITEM                        = 494,              //log
    LANGUAGE_ADDITEMSET                     = 495,              //log
    LANGUAGE_REMOVEITEM                     = 496,
    LANGUAGE_ITEM_CANNOT_CREATE             = 497,
    LANGUAGE_INSERT_GUILD_NAME              = 498,
    LANGUAGE_PLAYER_NOT_FOUND               = 499,
    LANGUAGE_PLAYER_IN_GUILD                = 500,
    LANGUAGE_GUILD_NOT_CREATED              = 501,
    LANGUAGE_NO_ITEMS_FROM_ITEMSET_FOUND    = 502,

    LANGUAGE_DISTANCE                       = 503,

    LANGUAGE_ITEM_SLOT                      = 504,
    LANGUAGE_ITEM_SLOT_NOT_EXIST            = 505,
    LANGUAGE_ITEM_ADDED_TO_SLOT             = 506,
    LANGUAGE_ITEM_SAVE_FAILED               = 507,
    LANGUAGE_ITEMLIST_SLOT                  = 508,
    LANGUAGE_ITEMLIST_MAIL                  = 509,
    LANGUAGE_ITEMLIST_AUCTION               = 510,

    LANGUAGE_WRONG_LINK_TYPE                = 511,
    LANGUAGE_ITEM_LIST_CHAT                 = 512,
    LANGUAGE_QUEST_LIST_CHAT                = 513,
    LANGUAGE_CREATURE_ENTRY_LIST_CHAT       = 514,
    LANGUAGE_CREATURE_LIST_CHAT             = 515,
    LANGUAGE_GO_ENTRY_LIST_CHAT             = 516,
    LANGUAGE_GO_LIST_CHAT                   = 517,
    LANGUAGE_ITEMSET_LIST_CHAT              = 518,
    LANGUAGE_TELE_LIST                      = 519,
    LANGUAGE_SPELL_LIST                     = 520,
    LANGUAGE_SKILL_LIST_CHAT                = 521,

    LANGUAGE_GAMEOBJECT_NOT_EXIST           = 522,

    LANGUAGE_GAMEOBJECT_CURRENT             = 523,              //log
    LANGUAGE_GAMEOBJECT_DETAIL              = 524,
    LANGUAGE_GAMEOBJECT_ADD                 = 525,

    LANGUAGE_MOVEGENS_LIST                  = 526,
    LANGUAGE_MOVEGENS_IDLE                  = 527,
    LANGUAGE_MOVEGENS_RANDOM                = 528,
    LANGUAGE_MOVEGENS_WAYPOINT              = 529,
    LANGUAGE_MOVEGENS_ANIMAL_RANDOM         = 530,
    LANGUAGE_MOVEGENS_CONFUSED              = 531,
    LANGUAGE_MOVEGENS_CHASE_PLAYER          = 532,
    LANGUAGE_MOVEGENS_CHASE_CREATURE        = 533,
    LANGUAGE_MOVEGENS_CHASE_NULL            = 534,
    LANGUAGE_MOVEGENS_HOME_CREATURE         = 535,
    LANGUAGE_MOVEGENS_HOME_PLAYER           = 536,
    LANGUAGE_MOVEGENS_FLIGHT                = 537,
    LANGUAGE_MOVEGENS_UNKNOWN               = 538,

    LANGUAGE_NPCINFO_CHAR                   = 539,
    LANGUAGE_NPCINFO_LEVEL                  = 540,
    LANGUAGE_NPCINFO_HEALTH                 = 541,
    LANGUAGE_NPCINFO_FLAGS                  = 542,
    LANGUAGE_NPCINFO_LOOT                   = 543,
    LANGUAGE_NPCINFO_POSITION               = 544,
    LANGUAGE_NPCINFO_VENDOR                 = 545,
    LANGUAGE_NPCINFO_TRAINER                = 546,
    LANGUAGE_NPCINFO_DUNGEON_ID             = 547,

    LANGUAGE_PINFO_ACCOUNT                  = 548,
    LANGUAGE_PINFO_LEVEL                    = 549,
    LANGUAGE_PINFO_MUTE                     = 550,
    LANGUAGE_PINFO_BAN                      = 453,
    LANGUAGE_PINFO_MAP_ONLINE               = 714,
    LANGUAGE_PINFO_MAP_OFFLINE              = 716,

    LANGUAGE_YOU_SET_EXPLORE_ALL            = 551,
    LANGUAGE_YOU_SET_EXPLORE_NOTHING        = 552,
    LANGUAGE_YOURS_EXPLORE_SET_ALL          = 553,
    LANGUAGE_YOURS_EXPLORE_SET_NOTHING      = 554,

    LANGUAGE_HOVER_ENABLED                  = 555,
    LANGUAGE_HOVER_DISABLED                 = 556,
    LANGUAGE_YOURS_LEVEL_UP                 = 557,
    LANGUAGE_YOURS_LEVEL_DOWN               = 558,
    LANGUAGE_YOURS_LEVEL_PROGRESS_RESET     = 559,
    LANGUAGE_EXPLORE_AREA                   = 560,
    LANGUAGE_UNEXPLORE_AREA                 = 561,

    LANGUAGE_UPDATE                         = 562,
    LANGUAGE_UPDATE_CHANGE                  = 563,
    LANGUAGE_TOO_BIG_INDEX                  = 564,
    LANGUAGE_SET_UINT                       = 565,              //log
    LANGUAGE_SET_UINT_FIELD                 = 566,
    LANGUAGE_SET_FLOAT                      = 567,              //log
    LANGUAGE_SET_FLOAT_FIELD                = 568,
    LANGUAGE_GET_UINT                       = 569,              //log
    LANGUAGE_GET_UINT_FIELD                 = 570,
    LANGUAGE_GET_FLOAT                      = 571,              //log
    LANGUAGE_GET_FLOAT_FIELD                = 572,
    LANGUAGE_SET_32BIT                      = 573,              //log
    LANGUAGE_SET_32BIT_FIELD                = 574,
    LANGUAGE_CHANGE_32BIT                   = 575,              //log
    LANGUAGE_CHANGE_32BIT_FIELD             = 576,

    LANGUAGE_INVISIBLE_INVISIBLE              = 577,
    LANGUAGE_INVISIBLE_VISIBLE                = 578,
    LANGUAGE_SELECTED_TARGET_NOT_HAVE_VICTIM  = 579,

    LANGUAGE_COMMAND_LEARN_ALL_DEFAULT_AND_QUEST = 580,
    LANGUAGE_COMMAND_NEAROBJMESSAGE         = 581,
    LANGUAGE_COMMAND_RAWPAWNTIMES           = 582,

    LANGUAGE_EVENT_ENTRY_LIST_CHAT          = 583,
    LANGUAGE_NOEVENTFOUND                   = 584,
    LANGUAGE_EVENT_NOT_EXIST                = 585,
    LANGUAGE_EVENT_INFO                     = 586,
    LANGUAGE_EVENT_ALREADY_ACTIVE           = 587,
    LANGUAGE_EVENT_NOT_ACTIVE               = 588,

    LANGUAGE_MOVEGENS_POINT                 = 589,
    LANGUAGE_MOVEGENS_FEAR                  = 590,
    LANGUAGE_MOVEGENS_DISTRACT              = 591,

    LANGUAGE_COMMAND_LEARN_ALL_RECIPES      = 592,
    LANGUAGE_BANLIST_ACCOUNTS               = 593,
    LANGUAGE_BANLIST_ACCOUNTS_HEADER        = 594,
    LANGUAGE_BANLIST_IPS                    = 595,
    LANGUAGE_BANLIST_IPS_HEADER             = 596,
    LANGUAGE_GMLIST                         = 597,
    LANGUAGE_GMLIST_HEADER                  = 598,
    LANGUAGE_GMLIST_EMPTY                   = 599,

    // End Level 3 list, continued at 1100

    // Battleground
    LANGUAGE_BG_A_WINS                      = 600,
    LANGUAGE_BG_H_WINS                      = 601,

    LANGUAGE_BG_WS_START_TWO_MINUTES        = 753,
    LANGUAGE_BG_WS_START_ONE_MINUTE         = 602,
    LANGUAGE_BG_WS_START_HALF_MINUTE        = 603,
    LANGUAGE_BG_WS_HAS_BEGUN                = 604,

    LANGUAGE_BG_WS_CAPTURED_HF              = 605,
    LANGUAGE_BG_WS_CAPTURED_AF              = 606,
    LANGUAGE_BG_WS_DROPPED_HF               = 607,
    LANGUAGE_BG_WS_DROPPED_AF               = 608,
    LANGUAGE_BG_WS_RETURNED_AF              = 609,
    LANGUAGE_BG_WS_RETURNED_HF              = 610,
    LANGUAGE_BG_WS_PICKEDUP_HF              = 611,
    LANGUAGE_BG_WS_PICKEDUP_AF              = 612,
    LANGUAGE_BG_WS_F_PLACED                 = 613,
    LANGUAGE_BG_WS_ALLIANCE_FLAG_RESPAWNED  = 614,
    LANGUAGE_BG_WS_HORDE_FLAG_RESPAWNED     = 615,

    LANGUAGE_BG_EY_START_TWO_MINUTES        = 755,
    LANGUAGE_BG_EY_START_ONE_MINUTE         = 636,
    LANGUAGE_BG_EY_START_HALF_MINUTE        = 637,
    LANGUAGE_BG_EY_HAS_BEGUN                = 638,

    LANGUAGE_BG_AB_ALLY                     = 650,
    LANGUAGE_BG_AB_HORDE                    = 651,
    LANGUAGE_BG_AB_NODE_STABLES             = 652,
    LANGUAGE_BG_AB_NODE_BLACKSMITH          = 653,
    LANGUAGE_BG_AB_NODE_FARM                = 654,
    LANGUAGE_BG_AB_NODE_LUMBER_MILL         = 655,
    LANGUAGE_BG_AB_NODE_GOLD_MINE           = 656,
    LANGUAGE_BG_AB_NODE_TAKEN               = 657,
    LANGUAGE_BG_AB_NODE_DEFENDED            = 658,
    LANGUAGE_BG_AB_NODE_ASSAULTED           = 659,
    LANGUAGE_BG_AB_NODE_CLAIMED             = 660,

    LANGUAGE_BG_AB_START_TWO_MINUTES        = 754,
    LANGUAGE_BG_AB_START_ONE_MINUTE         = 661,
    LANGUAGE_BG_AB_START_HALF_MINUTE        = 662,
    LANGUAGE_BG_AB_HAS_BEGUN                = 663,
    LANGUAGE_BG_AB_A_NEAR_VICTORY           = 664,
    LANGUAGE_BG_AB_H_NEAR_VICTORY           = 665,
    LANGUAGE_BG_MARK_BY_MAIL                = 666,

    LANGUAGE_BG_EY_HAS_TAKEN_A_M_TOWER      = 667,
    LANGUAGE_BG_EY_HAS_TAKEN_H_M_TOWER      = 668,
    LANGUAGE_BG_EY_HAS_TAKEN_A_D_RUINS      = 669,
    LANGUAGE_BG_EY_HAS_TAKEN_H_D_RUINS      = 670,
    LANGUAGE_BG_EY_HAS_TAKEN_A_B_TOWER      = 671,
    LANGUAGE_BG_EY_HAS_TAKEN_H_B_TOWER      = 672,
    LANGUAGE_BG_EY_HAS_TAKEN_A_F_RUINS      = 673,
    LANGUAGE_BG_EY_HAS_TAKEN_H_F_RUINS      = 674,
    LANGUAGE_BG_EY_HAS_LOST_A_M_TOWER       = 675,
    LANGUAGE_BG_EY_HAS_LOST_H_M_TOWER       = 676,
    LANGUAGE_BG_EY_HAS_LOST_A_D_RUINS       = 677,
    LANGUAGE_BG_EY_HAS_LOST_H_D_RUINS       = 678,
    LANGUAGE_BG_EY_HAS_LOST_A_B_TOWER       = 679,
    LANGUAGE_BG_EY_HAS_LOST_H_B_TOWER       = 680,
    LANGUAGE_BG_EY_HAS_LOST_A_F_RUINS       = 681,
    LANGUAGE_BG_EY_HAS_LOST_H_F_RUINS       = 682,
    LANGUAGE_BG_EY_HAS_TAKEN_FLAG           = 683,
    LANGUAGE_BG_EY_CAPTURED_FLAG_A          = 684,
    LANGUAGE_BG_EY_CAPTURED_FLAG_H          = 685,
    LANGUAGE_BG_EY_DROPPED_FLAG             = 686,
    LANGUAGE_BG_EY_RESETED_FLAG             = 687,

    LANGUAGE_ARENA_ONE_TOOLOW               = 700,
    LANGUAGE_ARENA_ONE_MINUTE               = 701,
    LANGUAGE_ARENA_THIRTY_SECONDS           = 702,
    LANGUAGE_ARENA_FIFTEEN_SECONDS          = 703,
    LANGUAGE_ARENA_HAS_BEGUN                = 704,

    LANGUAGE_WAIT_BEFORE_SPEAKING           = 705,
    LANGUAGE_NOT_EQUIPPED_ITEM              = 706,
    LANGUAGE_PLAYER_DND                     = 707,
    LANGUAGE_PLAYER_AFK                     = 708,
    LANGUAGE_PLAYER_DND_DEFAULT             = 709,
    LANGUAGE_PLAYER_AFK_DEFAULT             = 710,

    LANGUAGE_BG_QUEUE_ANNOUNCE_SELF         = 711,
    LANGUAGE_BG_QUEUE_ANNOUNCE_WORLD        = 712,
    LANGUAGE_YOUR_ARENA_LEVEL_REQ_ERROR     = 713,
//                                      = 714, see LANGUAGE_PINFO_MAP_ONLINE
    LANGUAGE_YOUR_BG_LEVEL_REQ_ERROR        = 715,
//                                      = 716, see LANGUAGE_PINFO_MAP_OFFLINE
    LANGUAGE_BG_STARTED_ANNOUNCE_WORLD      = 717,
    LANGUAGE_ARENA_QUEUE_ANNOUNCE_WORLD_JOIN= 718,
    LANGUAGE_ARENA_QUEUE_ANNOUNCE_WORLD_EXIT= 719,

    LANGUAGE_BG_GROUP_TOO_LARGE             = 720,              // "Your group is too large for this battleground. Please regroup to join."
    LANGUAGE_ARENA_GROUP_TOO_LARGE          = 721,              // "Your group is too large for this arena. Please regroup to join."
    LANGUAGE_ARENA_YOUR_TEAM_ONLY           = 722,              // "Your group has members not in your arena team. Please regroup to join."
    LANGUAGE_ARENA_NOT_ENOUGH_PLAYERS       = 723,              // "Your group does not have enough players to join this match."
    LANGUAGE_ARENA_GOLD_WINS                = 724,              // "The Gold Team wins!"
    LANGUAGE_ARENA_GREEN_WINS               = 725,              // "The Green Team wins!"
//                                      = 726, not used
    LANGUAGE_BG_GROUP_OFFLINE_MEMBER        = 727,              // "Your group has an offline member. Please remove him before joining."
    LANGUAGE_BG_GROUP_MIXED_FACTION         = 728,              // "Your group has players from the opposing faction. You can't join the battleground as a group."
    LANGUAGE_BG_GROUP_MIXED_LEVELS          = 729,              // "Your group has players from different battleground brakets. You can't join as group."
    LANGUAGE_BG_GROUP_MEMBER_ALREADY_IN_QUEUE = 730,            // "Someone in your party is already in this battleground queue. (S)he must leave it before joining as group."
    LANGUAGE_BG_GROUP_MEMBER_DESERTER       = 731,              // "Someone in your party is Deserter. You can't join as group."
    LANGUAGE_BG_GROUP_MEMBER_NO_FREE_QUEUE_SLOTS = 732,         // "Someone in your party is already in three battleground queues. You cannot join as group."

    LANGUAGE_CANNOT_TELE_TO_BG              = 733,              // "You cannot teleport to a battleground or arena map."
    LANGUAGE_CANNOT_SUMMON_TO_BG            = 734,              // "You cannot summon players to a battleground or arena map."
    LANGUAGE_CANNOT_GO_TO_BG_GM             = 735,              // "You must be in GM mode to teleport to a player in a battleground."
    LANGUAGE_CANNOT_GO_TO_BG_FROM_BG        = 736,              // "You cannot teleport to a battleground from another battleground. Please leave the current battleground first."
    LANGUAGE_DEBUG_ARENA_ON                 = 737,
    LANGUAGE_DEBUG_ARENA_OFF                = 738,
    LANGUAGE_DEBUG_BG_ON                    = 739,
    LANGUAGE_DEBUG_BG_OFF                   = 740,
    LANGUAGE_DIST_ARENA_POINTS_START        = 741,
    LANGUAGE_DIST_ARENA_POINTS_ONLINE_START = 742,
    LANGUAGE_DIST_ARENA_POINTS_ONLINE_END   = 743,
    LANGUAGE_DIST_ARENA_POINTS_TEAM_START   = 744,
    LANGUAGE_DIST_ARENA_POINTS_TEAM_END     = 745,
    LANGUAGE_DIST_ARENA_POINTS_END          = 746,
    LANGUAGE_BG_DISABLED                    = 747,
    LANGUAGE_ARENA_DISABLED                 = 748,
//                                      = 749, not used
    LANGUAGE_BATTLEGROUND_PREMATURE_FINISH_WARNING = 750,       // "Not enough players. This game will close in %u mins."
    LANGUAGE_BATTLEGROUND_PREMATURE_FINISH_WARNING_SECS = 751,  // "Not enough players. This game will close in %u seconds."
//                                      = 752, not used
//  LANGUAGE_BG_WS_START_TWO_MINUTES        = 753, - defined above
//  LANGUAGE_BG_AB_START_TWO_MINUTES        = 754, - defined above
//  LANGUAGE_BG_EY_START_TWO_MINUTES        = 755, - defined above

    // Room for BG/ARENA                = 773-784, 788-799 not used
    LANGUAGE_ARENA_TESTING                  = 785,
    LANGUAGE_AUTO_ANN                       = 786,
    LANGUAGE_ANNOUNCE_COLOR                 = 787,

    // in game strings
    LANGUAGE_PET_INVALID_NAME               = 800,
    LANGUAGE_NOT_ENOUGH_GOLD                = 801,
    LANGUAGE_NOT_FREE_TRADE_SLOTS           = 802,
    LANGUAGE_NOT_PARTNER_FREE_TRADE_SLOTS   = 803,
    LANGUAGE_YOU_NOT_HAVE_PERMISSION        = 804,
    LANGUAGE_UNKNOWN_LANGUAGE               = 805,
    LANGUAGE_NOT_LEARNED_LANGUAGE           = 806,
    LANGUAGE_NEED_CHARACTER_NAME            = 807,
    LANGUAGE_PLAYER_NOT_EXIST_OR_OFFLINE    = 808,
    LANGUAGE_ACCOUNT_FOR_PLAYER_NOT_FOUND   = 809,
    LANGUAGE_ACHIEVEMENT_EARNED             = 810,
    LANGUAGE_GUILD_MASTER                   = 811,
    LANGUAGE_GUILD_OFFICER                  = 812,
    LANGUAGE_GUILD_VETERAN                  = 813,
    LANGUAGE_GUILD_MEMBER                   = 814,
    LANGUAGE_GUILD_INITIATE                 = 815,
    LANGUAGE_ZONE_NOFLYZONE                 = 816,

    LANGUAGE_COMMAND_CREATURETEMPLATE_NOTFOUND = 817,
    LANGUAGE_COMMAND_CREATURESTORAGE_NOTFOUND  = 818,

    LANGUAGE_CHANNEL_CITY                   = 819,
    LANGUAGE_FAIL_ENTER_SPECTRAL_REALM      = 820,
    // Room for in-game strings           821-999 not used

    // Level 4 (CLI only commands)
    LANGUAGE_COMMAND_EXIT                   = 1000,
    LANGUAGE_ACCOUNT_DELETED                = 1001,
    LANGUAGE_ACCOUNT_NOT_DELETED_SQL_ERROR  = 1002,
    LANGUAGE_ACCOUNT_NOT_DELETED            = 1003,
    LANGUAGE_ACCOUNT_CREATED                = 1004,
    LANGUAGE_ACCOUNT_TOO_LONG               = 1005,
    LANGUAGE_ACCOUNT_ALREADY_EXIST          = 1006,
    LANGUAGE_ACCOUNT_NOT_CREATED_SQL_ERROR  = 1007,
    LANGUAGE_ACCOUNT_NOT_CREATED            = 1008,
    LANGUAGE_CHARACTER_DELETED              = 1009,
    LANGUAGE_ACCOUNT_LIST_HEADER            = 1010,
    LANGUAGE_ACCOUNT_LIST_ERROR             = 1011,
    LANGUAGE_ACCOUNT_LIST_BAR               = 1012,
    LANGUAGE_ACCOUNT_LIST_LINE              = 1013,
    LANGUAGE_ACCOUNT_LIST_EMPTY             = 1014,
    LANGUAGE_ACCOUNT_LIST_BAR_HEADER        = 1015,
    LANGUAGE_CHARACTER_DELETED_LIST_HEADER  = 1016,
    LANGUAGE_CHARACTER_DELETED_LIST_LINE_CONSOLE = 1017,
    LANGUAGE_CHARACTER_DELETED_LIST_BAR     = 1018,
    LANGUAGE_CHARACTER_DELETED_LIST_EMPTY   = 1019,
    LANGUAGE_CHARACTER_DELETED_RESTORE      = 1020,
    LANGUAGE_CHARACTER_DELETED_DELETE       = 1021,
    LANGUAGE_CHARACTER_DELETED_ERR_RENAME   = 1022,
    LANGUAGE_CHARACTER_DELETED_SKIP_ACCOUNT = 1023,
    LANGUAGE_CHARACTER_DELETED_SKIP_FULL    = 1024,
    LANGUAGE_CHARACTER_DELETED_SKIP_NAME    = 1025,
    LANGUAGE_CHARACTER_DELETED_LIST_LINE_CHAT = 1026,
    LANGUAGE_SQLDRIVER_QUERY_LOGGING_ENABLED  = 1027,
    LANGUAGE_SQLDRIVER_QUERY_LOGGING_DISABLED = 1028,
    // Room for more level 4              1029-1099 not used

    // Level 3 (continue)
    LANGUAGE_ACCOUNT_SETADDON               = 1100,
    LANGUAGE_MOTD_NEW                       = 1101,
    LANGUAGE_SENDMESSAGE                    = 1102,
    LANGUAGE_EVENT_ENTRY_LIST_CONSOLE       = 1103,
    LANGUAGE_CREATURE_ENTRY_LIST_CONSOLE    = 1104,
    LANGUAGE_ITEM_LIST_CONSOLE              = 1105,
    LANGUAGE_ITEMSET_LIST_CONSOLE           = 1106,
    LANGUAGE_GO_ENTRY_LIST_CONSOLE          = 1107,
    LANGUAGE_QUEST_LIST_CONSOLE             = 1108,
    LANGUAGE_SKILL_LIST_CONSOLE             = 1109,
    LANGUAGE_CREATURE_LIST_CONSOLE          = 1110,
    LANGUAGE_GO_LIST_CONSOLE                = 1111,
    LANGUAGE_FILE_OPEN_FAIL                 = 1112,
    LANGUAGE_ACCOUNT_CHARACTER_LIST_FULL    = 1113,
    LANGUAGE_DUMP_BROKEN                    = 1114,
    LANGUAGE_INVALID_CHARACTER_NAME         = 1115,
    LANGUAGE_INVALID_CHARACTER_GUID         = 1116,
    LANGUAGE_CHARACTER_GUID_IN_USE          = 1117,
    LANGUAGE_ITEMLIST_GUILD                 = 1118,
    LANGUAGE_MUST_MALE_OR_FEMALE            = 1119,
    LANGUAGE_YOU_CHANGE_GENDER              = 1120,
    LANGUAGE_YOUR_GENDER_CHANGED            = 1121,
    LANGUAGE_SKILL_VALUES                   = 1122,
    LANGUAGE_NO_PET_FOUND                   = 1123,
    LANGUAGE_WRONG_PET_TYPE                 = 1124,
    LANGUAGE_COMMAND_LEARN_PET_TALENTS      = 1125,
    LANGUAGE_RESET_PET_TALENTS              = 1126,
    LANGUAGE_RESET_PET_TALENTS_ONLINE       = 1127,
    LANGUAGE_TAXINODE_ENTRY_LIST_CHAT       = 1128,
    LANGUAGE_TAXINODE_ENTRY_LIST_CONSOLE    = 1129,
    LANGUAGE_COMMAND_EXPORT_DELETED_CHAR    = 1130,
    LANGUAGE_BANLIST_MATCHINGCHARACTER      = 1131,
    LANGUAGE_BANLIST_CHARACTERS             = 1132,
    LANGUAGE_BANLIST_CHARACTERS_HEADER      = 1133,
    LANGUAGE_ALLOW_TICKETS                  = 1134,
    LANGUAGE_DISALLOW_TICKETS               = 1135,
    LANGUAGE_CHARACTER_NOT_BANNED           = 1136,
    LANGUAGE_DEV_ON                         = 1137,
    LANGUAGE_DEV_OFF                        = 1138,
    LANGUAGE_MOVEGENS_FOLLOW_PLAYER         = 1139,
    LANGUAGE_MOVEGENS_FOLLOW_CREATURE       = 1140,
    LANGUAGE_MOVEGENS_FOLLOW_NULL           = 1141,
    LANGUAGE_MOVEGENS_EFFECT                = 1142,
    // Room for more level 3              1143-1199 not used

    // Debug commands
    LANGUAGE_CINEMATIC_NOT_EXIST            = 1200,
    LANGUAGE_MOVIE_NOT_EXIST                = 1201,
    LANGUAGE_DEBUG_AREATRIGGER_ON           = 1202,
    LANGUAGE_DEBUG_AREATRIGGER_OFF          = 1203,
    LANGUAGE_DEBUG_AREATRIGGER_REACHED      = 1204,
    // Room for more debug                1205-1299 not used

    // Isle of Conquest
    LANGUAGE_BG_IC_START_TWO_MINUTES        = 1205,
    LANGUAGE_BG_IC_START_ONE_MINUTE         = 1206,
    LANGUAGE_BG_IC_START_HALF_MINUTE        = 1207,
    LANGUAGE_BG_IC_HAS_BEGUN                = 1208,
    LANGUAGE_BG_IC_ALLIANCE_KEEP            = 1209,
    LANGUAGE_BG_IC_HORDE_KEEP               = 1210,
    LANGUAGE_BG_IC_TEAM_WINS                = 1211,
    LANGUAGE_BG_IC_WEST_GATE_DESTROYED      = 1212,
    LANGUAGE_BG_IC_EAST_GATE_DESTROYED      = 1213,
    LANGUAGE_BG_IC_SOUTH_GATE_DESTROYED     = 1214,
    LANGUAGE_BG_IC_NORTH_GATE_DESTROYED     = 1215,
    LANGUAGE_BG_IC_TEAM_ASSAULTED_NODE_1    = 1216,
    LANGUAGE_BG_IC_TEAM_DEFENDED_NODE       = 1217,
    LANGUAGE_BG_IC_TEAM_ASSAULTED_NODE_2    = 1218,
    LANGUAGE_BG_IC_TEAM_HAS_TAKEN_NODE      = 1219,
    LANGUAGE_BG_IC_WORKSHOP                 = 1220,
    LANGUAGE_BG_IC_DOCKS                    = 1221,
    LANGUAGE_BG_IC_REFINERY                 = 1222,
    LANGUAGE_BG_IC_QUARRY                   = 1223,
    LANGUAGE_BG_IC_HANGAR                   = 1224,
    LANGUAGE_BG_IC_ALLIANCE                 = 1300,
    LANGUAGE_BG_IC_HORDE                    = 1301,

    // Twin Peaks
    LANGUAGE_BG_TP_START_TWO_MINUTES        = 1230,
    LANGUAGE_BG_TP_START_ONE_MINUTE         = 1231,
    LANGUAGE_BG_TP_START_HALF_MINUTE        = 1232,
    LANGUAGE_BG_TP_HAS_BEGUN                = 1233,
    LANGUAGE_BG_TP_CAPTURED_HF              = 1234,
    LANGUAGE_BG_TP_CAPTURED_AF              = 1235,
    LANGUAGE_BG_TP_DROPPED_HF               = 1236,
    LANGUAGE_BG_TP_DROPPED_AF               = 1237,
    LANGUAGE_BG_TP_RETURNED_AF              = 1238,
    LANGUAGE_BG_TP_RETURNED_HF              = 1239,
    LANGUAGE_BG_TP_PICKEDUP_HF              = 1240,
    LANGUAGE_BG_TP_PICKEDUP_AF              = 1241,
    LANGUAGE_BG_TP_F_PLACED                 = 1242,
    LANGUAGE_BG_TP_ALLIANCE_FLAG_RESPAWNED  = 1243,
    LANGUAGE_BG_TP_HORDE_FLAG_RESPAWNED     = 1244,

    // FREE IDS                           1245-1249

    // Battle For Gilneas
    LANGUAGE_BG_BG_START_TWO_MINUTES        = 1250,
    LANGUAGE_BG_BG_START_ONE_MINUTE         = 1251,
    LANGUAGE_BG_BG_START_HALF_MINUTE        = 1252,
    LANGUAGE_BG_BG_HAS_BEGUN                = 1253,

    LANGUAGE_BG_BG_ALLY                     = 1254,
    LANGUAGE_BG_BG_HORDE                    = 1255,
    LANGUAGE_BG_BG_NODE_LIGHTHOUSE          = 1256,
    LANGUAGE_BG_BG_NODE_WATERWORKS          = 1257,
    LANGUAGE_BG_BG_NODE_MINE                = 1258,
    LANGUAGE_BG_BG_NODE_TAKEN               = 1259,
    LANGUAGE_BG_BG_NODE_DEFENDED            = 1260,
    LANGUAGE_BG_BG_NODE_ASSAULTED           = 1261,
    LANGUAGE_BG_BG_NODE_CLAIMED             = 1262,
    LANGUAGE_BG_BG_A_NEAR_VICTORY           = 1263,
    LANGUAGE_BG_BG_H_NEAR_VICTORY           = 1264,
    // FREE IDS                           1265-1299

    // AV
    LANGUAGE_BG_AV_ALLY                     = 1300,
    LANGUAGE_BG_AV_HORDE                    = 1301,
    LANGUAGE_BG_AV_TOWER_TAKEN              = 1302,
    LANGUAGE_BG_AV_TOWER_ASSAULTED          = 1303,
    LANGUAGE_BG_AV_TOWER_DEFENDED           = 1304,
    LANGUAGE_BG_AV_GRAVE_TAKEN              = 1305,
    LANGUAGE_BG_AV_GRAVE_DEFENDED           = 1306,
    LANGUAGE_BG_AV_GRAVE_ASSAULTED          = 1307,

    LANGUAGE_BG_AV_MINE_TAKEN               = 1308,
    LANGUAGE_BG_AV_MINE_NORTH               = 1309,
    LANGUAGE_BG_AV_MINE_SOUTH               = 1310,

    LANGUAGE_BG_AV_NODE_GRAVE_STORM_AID     = 1311,
    LANGUAGE_BG_AV_NODE_TOWER_DUN_S         = 1312,
    LANGUAGE_BG_AV_NODE_TOWER_DUN_N         = 1313,
    LANGUAGE_BG_AV_NODE_GRAVE_STORMPIKE     = 1314,
    LANGUAGE_BG_AV_NODE_TOWER_ICEWING       = 1315,
    LANGUAGE_BG_AV_NODE_GRAVE_STONE         = 1316,
    LANGUAGE_BG_AV_NODE_TOWER_STONE         = 1317,
    LANGUAGE_BG_AV_NODE_GRAVE_SNOW          = 1318,
    LANGUAGE_BG_AV_NODE_TOWER_ICE           = 1319,
    LANGUAGE_BG_AV_NODE_GRAVE_ICE           = 1320,
    LANGUAGE_BG_AV_NODE_TOWER_POINT         = 1321,
    LANGUAGE_BG_AV_NODE_GRAVE_FROST         = 1322,
    LANGUAGE_BG_AV_NODE_TOWER_FROST_E       = 1323,
    LANGUAGE_BG_AV_NODE_TOWER_FROST_W       = 1324,
    LANGUAGE_BG_AV_NODE_GRAVE_FROST_HUT     = 1325,

    LANGUAGE_BG_AV_START_ONE_MINUTE         = 1326,
    LANGUAGE_BG_AV_START_HALF_MINUTE        = 1327,
    LANGUAGE_BG_AV_HAS_BEGUN                = 1328,
    LANGUAGE_BG_AV_A_NEAR_LOSE              = 1329,
    LANGUAGE_BG_AV_H_NEAR_LOSE              = 1330,
    LANGUAGE_BG_AV_H_CAPTAIN_DEAD           = 1331,
    LANGUAGE_BG_AV_A_CAPTAIN_DEAD           = 1332,
    LANGUAGE_BG_AV_START_TWO_MINUTES        = 1333,
    // FREE IDS                           1334-1999

    // Ticket Strings 2000-2029
    LANGUAGE_COMMAND_TICKETNEW              = 2000,
    LANGUAGE_COMMAND_TICKETUPDATED          = 2001,
    LANGUAGE_COMMAND_TICKETPLAYERABANDON    = 2002,
    LANGUAGE_COMMAND_TICKETCLOSED           = 2003,
    LANGUAGE_COMMAND_TICKETDELETED          = 2004,
    LANGUAGE_COMMAND_TICKETNOTEXIST         = 2005,
    LANGUAGE_COMMAND_TICKETCLOSEFIRST       = 2006,
    LANGUAGE_COMMAND_TICKETALREADYASSIGNED  = 2007,
    LANGUAGE_COMMAND_TICKETRELOAD           = 2008,
    LANGUAGE_COMMAND_TICKETSHOWLIST         = 2009,
    LANGUAGE_COMMAND_TICKETSHOWONLINELIST   = 2010,
    LANGUAGE_COMMAND_TICKETSHOWCLOSEDLIST   = 2011,
    LANGUAGE_COMMAND_TICKETASSIGNERROR_A    = 2012,
    LANGUAGE_COMMAND_TICKETASSIGNERROR_B    = 2013,
    LANGUAGE_COMMAND_TICKETNOTASSIGNED      = 2014,
    LANGUAGE_COMMAND_TICKETUNASSIGNSECURITY = 2015,
    LANGUAGE_COMMAND_TICKETCANNOTCLOSE      = 2016,
    LANGUAGE_COMMAND_TICKETLISTGUID         = 2017,
    LANGUAGE_COMMAND_TICKETLISTNAME         = 2018,
    LANGUAGE_COMMAND_TICKETLISTAGE          = 2019,
    LANGUAGE_COMMAND_TICKETLISTASSIGNEDTO   = 2020,
    LANGUAGE_COMMAND_TICKETLISTUNASSIGNED   = 2021,
    LANGUAGE_COMMAND_TICKETLISTMESSAGE      = 2022,
    LANGUAGE_COMMAND_TICKETLISTCOMMENT      = 2023,
    LANGUAGE_COMMAND_TICKETLISTADDCOMMENT   = 2024,
    LANGUAGE_COMMAND_TICKETLISTAGECREATE    = 2025,
    LANGUAGE_COMMAND_TICKETSHOWESCALATEDLIST = 2026,
    LANGUAGE_COMMAND_TICKETPENDING          = 2027,
    LANGUAGE_COMMAND_TICKETRESET            = 2028,

    // SkyFire strings                    5000-9999
    LANGUAGE_COMMAND_FREEZE                 = 5000,
    LANGUAGE_COMMAND_FREEZE_ERROR           = 5001,
    LANGUAGE_COMMAND_FREEZE_WRONG           = 5002,
    LANGUAGE_COMMAND_UNFREEZE               = 5003,
    LANGUAGE_COMMAND_NO_FROZEN_PLAYERS      = 5004,
    LANGUAGE_COMMAND_LIST_FREEZE            = 5005,
    LANGUAGE_COMMAND_FROZEN_PLAYERS         = 5006,
    LANGUAGE_INSTANCE_RAID_GROUP_ONLY       = 5007,
    LANGUAGE_INSTANCE_CLOSED                = 5008,
    LANGUAGE_COMMAND_PLAYED_TO_ALL          = 5009,
    LANGUAGE_NPCINFO_LINKGUID               = 5010,
    LANGUAGE_TELEPORTED_TO_BY_CONSOLE       = 5011,
    // for command lookup map
    LANGUAGE_COMMAND_NOMAPFOUND             = 5012,
    LANGUAGE_CONTINENT                      = 5013,
    LANGUAGE_INSTANCE                       = 5014,
    LANGUAGE_BATTLEGROUND                   = 5015,
    LANGUAGE_ARENA                          = 5016,
    LANGUAGE_RAID                           = 5017,
    LANGUAGE_HEROIC                         = 5018,
    LANGUAGE_MOUNTABLE                      = 5019,
    LANGUAGE_NPCINFO_PHASEMASK              = 5020,
    LANGUAGE_NPCINFO_ARMOR                  = 5021,
    LANGUAGE_CHANNEL_ENABLE_OWNERSHIP       = 5022,
    LANGUAGE_CHANNEL_DISABLE_OWNERSHIP      = 5023,
    LANGUAGE_GOINFO_ENTRY                   = 5024,
    LANGUAGE_GOINFO_TYPE                    = 5025,
    LANGUAGE_GOINFO_DISPLAYID               = 5026,
    LANGUAGE_GOINFO_NAME                    = 5027,
    LANGUAGE_GOINFO_LOOTID                  = 5028,
    LANGUAGE_COMMAND_LOOKUP_MAX_RESULTS     = 5029,
    LANGUAGE_FLEE                           = 5030,
    LANGUAGE_NPCINFO_AIINFO                 = 5031,
    // Room for more SkyFire strings      5032-9999

    // Level requirement notifications
    LANGUAGE_SAY_REQ                        = 6604,
    LANGUAGE_WHISPER_REQ                    = 6605,
    LANGUAGE_CHANNEL_REQ                    = 6606,
    LANGUAGE_AUCTION_REQ                    = 6607,
    LANGUAGE_TICKET_REQ                     = 6608,
    LANGUAGE_TRADE_REQ                      = 6609,
    LANGUAGE_TRADE_OTHER_REQ                = 6610,
    LANGUAGE_MAIL_SENDER_REQ                = 6611,
    LANGUAGE_MAIL_RECEIVER_REQ              = 6612,

    // Used for GM Announcements
    LANGUAGE_GM_BROADCAST                    = 6613,
    LANGUAGE_GM_NOTIFY                       = 6614,
    LANGUAGE_GM_ANNOUNCE_COLOR               = 6615,

    LANGUAGE_GM_SILENCE                      = 6616,              // "Silence is ON for %s" - Spell 1852

    LANGUAGE_WORLD_CLOSED                    = 7523,
    LANGUAGE_WORLD_OPENED                    = 7524,

    // Use for not-in-offcial-sources patches
    //                                    10000-10999
    // opvp hp
    LANGUAGE_OPVP_HP_CAPTURE_OVERLOOK_H     = 10001,
    LANGUAGE_OPVP_HP_CAPTURE_OVERLOOK_A     = 10002,
    LANGUAGE_OPVP_HP_CAPTURE_STADIUM_H      = 10003,
    LANGUAGE_OPVP_HP_CAPTURE_STADIUM_A      = 10004,
    LANGUAGE_OPVP_HP_CAPTURE_BROKENHILL_H   = 10005,
    LANGUAGE_OPVP_HP_CAPTURE_BROKENHILL_A   = 10006,
    LANGUAGE_OPVP_HP_LOSE_OVERLOOK_H       = 10007,
    LANGUAGE_OPVP_HP_LOSE_OVERLOOK_A       = 10008,
    LANGUAGE_OPVP_HP_LOSE_STADIUM_H        = 10009,
    LANGUAGE_OPVP_HP_LOSE_STADIUM_A        = 10010,
    LANGUAGE_OPVP_HP_LOSE_BROKENHILL_H     = 10011,
    LANGUAGE_OPVP_HP_LOSE_BROKENHILL_A     = 10012,
    // opvp zm
    LANGUAGE_OPVP_ZM_CAPTURE_WEST_H         = 10013,
    LANGUAGE_OPVP_ZM_CAPTURE_WEST_A         = 10014,
    LANGUAGE_OPVP_ZM_CAPTURE_EAST_H         = 10015,
    LANGUAGE_OPVP_ZM_CAPTURE_EAST_A         = 10016,
    LANGUAGE_OPVP_ZM_CAPTURE_GY_H           = 10017,
    LANGUAGE_OPVP_ZM_CAPTURE_GY_A           = 10018,
    LANGUAGE_OPVP_ZM_LOSE_WEST_H           = 10019,
    LANGUAGE_OPVP_ZM_LOSE_WEST_A           = 10020,
    LANGUAGE_OPVP_ZM_LOSE_EAST_H           = 10021,
    LANGUAGE_OPVP_ZM_LOSE_EAST_A           = 10022,
    LANGUAGE_OPVP_ZM_LOSE_GY_H             = 10023,
    LANGUAGE_OPVP_ZM_LOSE_GY_A             = 10024,
    // opvp na
    LANGUAGE_OPVP_NA_CAPTURE_H              = 10025,
    LANGUAGE_OPVP_NA_CAPTURE_A              = 10026,
    LANGUAGE_OPVP_NA_LOSE_H                = 10027,
    LANGUAGE_OPVP_NA_LOSE_A                = 10028,
    // opvp tf
    LANGUAGE_OPVP_TF_CAPTURE_H              = 10029,
    LANGUAGE_OPVP_TF_CAPTURE_A              = 10030,
    LANGUAGE_OPVP_TF_LOSE_H                = 10031,
    LANGUAGE_OPVP_TF_LOSE_A                = 10032,
    // opvp ep
    LANGUAGE_OPVP_EP_CAPTURE_NPT_H          = 10033,
    LANGUAGE_OPVP_EP_CAPTURE_NPT_A          = 10034,
    LANGUAGE_OPVP_EP_CAPTURE_EWT_H          = 10035,
    LANGUAGE_OPVP_EP_CAPTURE_EWT_A          = 10036,
    LANGUAGE_OPVP_EP_CAPTURE_CGT_H          = 10037,
    LANGUAGE_OPVP_EP_CAPTURE_CGT_A          = 10038,
    LANGUAGE_OPVP_EP_CAPTURE_PWT_H          = 10039,
    LANGUAGE_OPVP_EP_CAPTURE_PWT_A          = 10040,
    LANGUAGE_OPVP_EP_LOSE_NPT_H            = 10041,
    LANGUAGE_OPVP_EP_LOSE_NPT_A            = 10042,
    LANGUAGE_OPVP_EP_LOSE_EWT_H            = 10043,
    LANGUAGE_OPVP_EP_LOSE_EWT_A            = 10044,
    LANGUAGE_OPVP_EP_LOSE_CGT_H            = 10045,
    LANGUAGE_OPVP_EP_LOSE_CGT_A            = 10046,
    LANGUAGE_OPVP_EP_LOSE_PWT_H            = 10047,
    LANGUAGE_OPVP_EP_LOSE_PWT_A            = 10048,
    // opvp si
    LANGUAGE_OPVP_SI_CAPTURE_H              = 10049,
    LANGUAGE_OPVP_SI_CAPTURE_A              = 10050,
    // opvp gossips
    LANGUAGE_OPVP_EP_FLIGHT_NPT             = 10051,
    LANGUAGE_OPVP_EP_FLIGHT_EWT             = 10052,
    LANGUAGE_OPVP_EP_FLIGHT_CGT             = 10053,
    LANGUAGE_OPVP_ZM_GOSSIP_ALLIANCE        = 10054,
    LANGUAGE_OPVP_ZM_GOSSIP_HORDE           = 10055,

    LANGUAGE_BG_SA_START_TWO_MINUTES            = 10056,
    LANGUAGE_BG_SA_START_ONE_MINUTE             = 10057,
    LANGUAGE_BG_SA_START_HALF_MINUTE            = 10058,
    LANGUAGE_BG_SA_HAS_BEGUN                    = 10059,
    LANGUAGE_BG_SA_IS_UNDER_ATTACK              = 10060, //The %s is under attack!
    LANGUAGE_BG_SA_WAS_DESTROYED                = 10061, //The %s was destroyed!
    LANGUAGE_BG_SA_ROUND_ONE_END                = 10062, //Round 1 - finished!
    LANGUAGE_BG_SA_ALLIANCE_CAPTURED_RELIC      = 10063, //The Alliance captured the titan portal!
    LANGUAGE_BG_SA_HORDE_CAPTURED_RELIC         = 10064, //The Horde captured the titan portal!
    LANGUAGE_BG_SA_ROUND_TWO_ONE_MINUTE         = 10065, //Round 2 of the Battle for the Strand of the Ancients begins in 1 minute.
    LANGUAGE_BG_SA_ROUND_TWO_START_HALF_MINUTE  = 10066, //Round 2 begins in 30 seconds. Prepare yourselves!
    LANGUAGE_BG_SA_CHAMBER_BREACHED             = 10067, //The chamber has been breached! The titan relic is vulnerable!
    LANGUAGE_BG_SA_A_GY_SOUTH                   = 10068, //The Alliance captured the South Graveyard!
    LANGUAGE_BG_SA_A_GY_WEST                    = 10069, //The Alliance captured the West Graveyard!
    LANGUAGE_BG_SA_A_GY_EAST                    = 10070, //The Alliance captured the East Graveyard!
    LANGUAGE_BG_SA_H_GY_SOUTH                   = 10071, //The Horde captured the South Graveyard!
    LANGUAGE_BG_SA_H_GY_WEST                    = 10072, //The Horde captured the West Graveyard!
    LANGUAGE_BG_SA_H_GY_EAST                    = 10073, //The Horde captured the East Graveyard!

    // Use for custom patches             11000-11999
    LANGUAGE_AUTO_BROADCAST                 = 11000,
    LANGUAGE_INVALID_REALMID                = 11001,

    // NOT RESERVED IDS                   12000-1999999999
    // `db_script_string` table index     2000000000-2000009999 (MIN_DB_SCRIPT_STRING_ID-MAX_DB_SCRIPT_STRING_ID)
    // For other tables maybe             2000010000-2147483647 (max index)
};
#endif
