
ALTER TABLE `creature_text`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `currency_loot`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `disenchant_loot_template`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `guild_rewards`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `guild_xp_for_level`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `pool_quest_save`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `warden_checks`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `achievement_dbc`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;

ALTER TABLE `game_event_seasonal_questrelation`
ROW_FORMAT=DEFAULT ENGINE=MYISAM;
