// -*- C++ -*-
// $Id: Obstack.cpp 97400 2013-10-31 10:44:50Z mhengstmengel $

#include "ace/Obstack.h"

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_SINGLETON_TEMPLATE_INSTANTIATION(ACE_Obstack_T <char>;);

ACE_END_VERSIONED_NAMESPACE_DECL
