
// -*- C++ -*-
// $Id: Version.h 95779 2012-05-19 12:30:41Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 1
#define ACE_BETA_VERSION 2
#define ACE_VERSION "6.1.2"
